<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'name' => 'Sarah Wijaya',
                'email' => 'sarah.wijaya@maknaonline.com',
                'phone' => '81234567890',
                'address' => 'Jl. Sudirman No. 123, Jakarta Pusat',
                'position' => 'Founder',
                'salary' => 15000000,
                'date_of_birth' => '1988-03-15',
                'date_of_join' => '2020-01-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '1234567890',
                'instagram' => 'sarah_wijaya_makna',
                'note' => 'Founder dan CEO Makna Online. Memiliki pengalaman 10+ tahun di industri wedding organizer.',
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'michael.chen@maknaonline.com',
                'phone' => '81234567891',
                'address' => 'Jl. Gatot Subroto No. 456, Jakarta Selatan',
                'position' => 'Co Founder',
                'salary' => 12000000,
                'date_of_birth' => '1990-07-22',
                'date_of_join' => '2020-01-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '2345678901',
                'instagram' => 'michael_chen_makna',
                'note' => 'Co-Founder dan COO. Bertanggung jawab atas operasional dan strategi bisnis.',
            ],
            [
                'name' => 'Rani Sari Dewi',
                'email' => 'rani.sari@maknaonline.com',
                'phone' => '81234567892',
                'address' => 'Jl. Kemang Raya No. 789, Jakarta Selatan',
                'position' => 'Account Manager',
                'salary' => 8000000,
                'date_of_birth' => '1992-11-08',
                'date_of_join' => '2021-03-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '3456789012',
                'instagram' => 'rani_sari_makna',
                'note' => 'Account Manager senior dengan track record excellent dalam menangani klien premium.',
            ],
            [
                'name' => 'David Pranata',
                'email' => 'david.pranata@maknaonline.com',
                'phone' => '81234567893',
                'address' => 'Jl. Senopati No. 321, Jakarta Selatan',
                'position' => 'Account Manager',
                'salary' => 7500000,
                'date_of_birth' => '1993-05-12',
                'date_of_join' => '2021-08-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '4567890123',
                'instagram' => 'david_pranata_makna',
                'note' => 'Account Manager yang fokus pada segmen pasar menengah ke atas.',
            ],
            [
                'name' => 'Luna Kartika',
                'email' => 'luna.kartika@maknaonline.com',
                'phone' => '81234567894',
                'address' => 'Jl. Pejaten Raya No. 654, Jakarta Selatan',
                'position' => 'Event Manager',
                'salary' => 9000000,
                'date_of_birth' => '1989-09-30',
                'date_of_join' => '2020-06-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '5678901234',
                'instagram' => 'luna_kartika_makna',
                'note' => 'Event Manager berpengalaman dengan keahlian koordinasi vendor dan timeline management.',
            ],
            [
                'name' => 'Agus Hermawan',
                'email' => 'agus.hermawan@maknaonline.com',
                'phone' => '81234567895',
                'address' => 'Jl. Fatmawati No. 987, Jakarta Selatan',
                'position' => 'Event Manager',
                'salary' => 8500000,
                'date_of_birth' => '1991-12-18',
                'date_of_join' => '2021-01-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '6789012345',
                'instagram' => 'agus_hermawan_makna',
                'note' => 'Event Manager yang spesialis dalam wedding outdoor dan destination wedding.',
            ],
            [
                'name' => 'Sinta Maharani',
                'email' => 'sinta.maharani@maknaonline.com',
                'phone' => '81234567896',
                'address' => 'Jl. Radio Dalam No. 147, Jakarta Selatan',
                'position' => 'Finance',
                'salary' => 7000000,
                'date_of_birth' => '1994-04-25',
                'date_of_join' => '2021-11-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '7890123456',
                'instagram' => 'sinta_maharani_finance',
                'note' => 'Finance Manager yang menangani semua aspek keuangan dan accounting perusahaan.',
            ],
            [
                'name' => 'Eko Prasetyo',
                'email' => 'eko.prasetyo@maknaonline.com',
                'phone' => '81234567897',
                'address' => 'Jl. Cilandak KKO No. 258, Jakarta Selatan',
                'position' => 'Crew',
                'salary' => 5500000,
                'date_of_birth' => '1995-08-14',
                'date_of_join' => '2022-02-14',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '8901234567',
                'instagram' => 'eko_prasetyo_crew',
                'note' => 'Crew senior yang ahli dalam setup dekorasi dan koordinasi hari-H.',
            ],
            [
                'name' => 'Maya Indira',
                'email' => 'maya.indira@maknaonline.com',
                'phone' => '81234567898',
                'address' => 'Jl. Ampera Raya No. 369, Jakarta Selatan',
                'position' => 'Crew',
                'salary' => 5000000,
                'date_of_birth' => '1996-01-20',
                'date_of_join' => '2022-06-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '9012345678',
                'instagram' => 'maya_indira_crew',
                'note' => 'Crew yang spesialis dalam koordinasi catering dan vendor makanan.',
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@maknaonline.com',
                'phone' => '81234567899',
                'address' => 'Jl. Pasar Minggu No. 741, Jakarta Selatan',
                'position' => 'Crew',
                'salary' => 4800000,
                'date_of_birth' => '1997-06-03',
                'date_of_join' => '2023-01-15',
                'date_of_out' => '2026-12-31',
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '0123456789',
                'instagram' => 'budi_santoso_crew',
                'note' => 'Mantan crew yang resign untuk melanjutkan studi S2.',
            ],
            [
                'name' => 'Citra Anggraini',
                'email' => 'citra.anggraini@maknaonline.com',
                'phone' => '81234567900',
                'address' => 'Jl. Mampang Prapatan No. 111, Jakarta Selatan',
                'position' => 'Wedding Consultant',
                'salary' => 7000000,
                'date_of_birth' => '1991-06-25',
                'date_of_join' => '2021-11-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '1123456789',
                'instagram' => 'citra_anggraini_makna',
                'note' => 'Wedding consultant yang specialized dalam konsep intimate dan outdoor wedding.',
            ],
            [
                'name' => 'Dimas Pratama',
                'email' => 'dimas.pratama@maknaonline.com',
                'phone' => '81234567901',
                'address' => 'Jl. Kuningan Barat No. 222, Jakarta Selatan',
                'position' => 'Wedding Coordinator',
                'salary' => 6500000,
                'date_of_birth' => '1993-08-14',
                'date_of_join' => '2022-02-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '2234567890',
                'instagram' => 'dimas_pratama_makna',
                'note' => 'Wedding coordinator dengan pengalaman dalam traditional dan modern wedding.',
            ],
            [
                'name' => 'Elsa Maharani',
                'email' => 'elsa.maharani@maknaonline.com',
                'phone' => '81234567902',
                'address' => 'Jl. Warung Buncit No. 333, Jakarta Selatan',
                'position' => 'Decoration Specialist',
                'salary' => 7500000,
                'date_of_birth' => '1990-12-03',
                'date_of_join' => '2021-05-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '3345678901',
                'instagram' => 'elsa_maharani_makna',
                'note' => 'Decoration specialist dengan keahlian dalam luxury dan minimalist design.',
            ],
            [
                'name' => 'Farid Kurniawan',
                'email' => 'farid.kurniawan@maknaonline.com',
                'phone' => '81234567903',
                'address' => 'Jl. Pancoran Mas No. 444, Depok',
                'position' => 'Vendor Relations',
                'salary' => 6800000,
                'date_of_birth' => '1992-04-21',
                'date_of_join' => '2021-09-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '4456789012',
                'instagram' => 'farid_kurniawan_makna',
                'note' => 'Vendor relations specialist yang mengelola kemitraan dengan supplier.',
            ],
            [
                'name' => 'Gina Sari',
                'email' => 'gina.sari@maknaonline.com',
                'phone' => '81234567904',
                'address' => 'Jl. Kalibata Raya No. 555, Jakarta Selatan',
                'position' => 'Marketing Specialist',
                'salary' => 7200000,
                'date_of_birth' => '1994-01-17',
                'date_of_join' => '2022-03-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '5567890123',
                'instagram' => 'gina_sari_makna',
                'note' => 'Marketing specialist dengan fokus pada digital marketing dan social media.',
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra.wijaya@maknaonline.com',
                'phone' => '81234567905',
                'address' => 'Jl. Cilandak KKO No. 666, Jakarta Selatan',
                'position' => 'Project Manager',
                'salary' => 9500000,
                'date_of_birth' => '1987-10-09',
                'date_of_join' => '2020-08-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '6678901234',
                'instagram' => 'hendra_wijaya_makna',
                'note' => 'Senior project manager dengan pengalaman menangani multi-event projects.',
            ],
            [
                'name' => 'Indira Putri',
                'email' => 'indira.putri@maknaonline.com',
                'phone' => '81234567906',
                'address' => 'Jl. Ragunan No. 777, Jakarta Selatan',
                'position' => 'Customer Service',
                'salary' => 5500000,
                'date_of_birth' => '1995-07-28',
                'date_of_join' => '2022-06-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '7789012345',
                'instagram' => 'indira_putri_makna',
                'note' => 'Customer service representative dengan excellent communication skills.',
            ],
            [
                'name' => 'Joko Susanto',
                'email' => 'joko.susanto@maknaonline.com',
                'phone' => '81234567907',
                'address' => 'Jl. Pasar Minggu No. 888, Jakarta Selatan',
                'position' => 'Logistics Coordinator',
                'salary' => 6200000,
                'date_of_birth' => '1991-03-11',
                'date_of_join' => '2021-12-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '8890123456',
                'instagram' => 'joko_susanto_makna',
                'note' => 'Logistics coordinator yang mengatur transportasi dan equipment delivery.',
            ],
            [
                'name' => 'Kartika Dewi',
                'email' => 'kartika.dewi@maknaonline.com',
                'phone' => '81234567908',
                'address' => 'Jl. Ampera Raya No. 999, Jakarta Selatan',
                'position' => 'HR Specialist',
                'salary' => 7800000,
                'date_of_birth' => '1989-11-05',
                'date_of_join' => '2020-10-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '9901234567',
                'instagram' => 'kartika_dewi_makna',
                'note' => 'HR specialist yang mengelola recruitment dan employee development.',
            ],
            [
                'name' => 'Lestari Indah',
                'email' => 'lestari.indah@maknaonline.com',
                'phone' => '81234567909',
                'address' => 'Jl. Cipete Raya No. 101, Jakarta Selatan',
                'position' => 'Content Creator',
                'salary' => 6700000,
                'date_of_birth' => '1993-09-19',
                'date_of_join' => '2022-01-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '1012345678',
                'instagram' => 'lestari_indah_makna',
                'note' => 'Content creator untuk social media dan marketing materials.',
            ],
            [
                'name' => 'Mario Gunawan',
                'email' => 'mario.gunawan@maknaonline.com',
                'phone' => '81234567910',
                'address' => 'Jl. Bintaro Permai No. 202, Tangerang Selatan',
                'position' => 'IT Support',
                'salary' => 8200000,
                'date_of_birth' => '1990-05-26',
                'date_of_join' => '2021-07-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '2123456789',
                'instagram' => 'mario_gunawan_makna',
                'note' => 'IT support specialist yang mengelola sistem teknologi perusahaan.',
            ],
            [
                'name' => 'Nadia Sari',
                'email' => 'nadia.sari@maknaonline.com',
                'phone' => '81234567911',
                'address' => 'Jl. Kemang Pratama No. 303, Bekasi',
                'position' => 'Bridal Consultant',
                'salary' => 7300000,
                'date_of_birth' => '1992-08-12',
                'date_of_join' => '2021-10-05',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '3234567890',
                'instagram' => 'nadia_sari_makna',
                'note' => 'Bridal consultant dengan keahlian dalam fashion dan beauty advisory.',
            ],
            [
                'name' => 'Oscar Pradipta',
                'email' => 'oscar.pradipta@maknaonline.com',
                'phone' => '81234567912',
                'address' => 'Jl. Cibubur Country No. 404, Depok',
                'position' => 'Audio Visual Specialist',
                'salary' => 7600000,
                'date_of_birth' => '1991-12-30',
                'date_of_join' => '2021-04-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '4345678901',
                'instagram' => 'oscar_pradipta_makna',
                'note' => 'Audio visual specialist untuk sound system dan lighting events.',
            ],
            [
                'name' => 'Putri Maharani',
                'email' => 'putri.maharani@maknaonline.com',
                'phone' => '81234567913',
                'address' => 'Jl. BSD Raya No. 505, Tangerang Selatan',
                'position' => 'Wedding Stylist',
                'salary' => 7100000,
                'date_of_birth' => '1994-04-07',
                'date_of_join' => '2022-05-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '5456789012',
                'instagram' => 'putri_maharani_makna',
                'note' => 'Wedding stylist dengan specialty dalam contemporary dan rustic themes.',
            ],
            [
                'name' => 'Qori Rahman',
                'email' => 'qori.rahman@maknaonline.com',
                'phone' => '81234567914',
                'address' => 'Jl. Serpong Raya No. 606, Tangerang Selatan',
                'position' => 'Quality Control',
                'salary' => 6900000,
                'date_of_birth' => '1990-01-24',
                'date_of_join' => '2021-08-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '6567890123',
                'instagram' => 'qori_rahman_makna',
                'note' => 'Quality control specialist yang memastikan standar kualitas service.',
            ],
            [
                'name' => 'Ratna Sari',
                'email' => 'ratna.sari@maknaonline.com',
                'phone' => '81234567915',
                'address' => 'Jl. Pondok Indah No. 707, Jakarta Selatan',
                'position' => 'Catering Coordinator',
                'salary' => 6600000,
                'date_of_birth' => '1993-06-13',
                'date_of_join' => '2022-02-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '7678901234',
                'instagram' => 'ratna_sari_makna',
                'note' => 'Catering coordinator yang mengelola F&B vendor partnerships.',
            ],
            [
                'name' => 'Sandi Nugroho',
                'email' => 'sandi.nugroho@maknaonline.com',
                'phone' => '81234567916',
                'address' => 'Jl. Lebak Bulus No. 808, Jakarta Selatan',
                'position' => 'Transportation Manager',
                'salary' => 7400000,
                'date_of_birth' => '1988-10-01',
                'date_of_join' => '2020-12-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '8789012345',
                'instagram' => 'sandi_nugroho_makna',
                'note' => 'Transportation manager yang mengatur fleet dan logistics transportation.',
            ],
            [
                'name' => 'Tia Melinda',
                'email' => 'tia.melinda@maknaonline.com',
                'phone' => '81234567917',
                'address' => 'Jl. Ciputat Raya No. 909, Tangerang Selatan',
                'position' => 'Event Assistant',
                'salary' => 5800000,
                'date_of_birth' => '1995-03-16',
                'date_of_join' => '2022-07-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '9890123456',
                'instagram' => 'tia_melinda_makna',
                'note' => 'Event assistant yang membantu koordinasi on-site event execution.',
            ],
            [
                'name' => 'Usman Hakim',
                'email' => 'usman.hakim@maknaonline.com',
                'phone' => '81234567918',
                'address' => 'Jl. Pamulang No. 1010, Tangerang Selatan',
                'position' => 'Security Coordinator',
                'salary' => 6300000,
                'date_of_birth' => '1987-11-22',
                'date_of_join' => '2020-09-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '1098765432',
                'instagram' => 'usman_hakim_makna',
                'note' => 'Security coordinator untuk event safety dan guest management.',
            ],
            [
                'name' => 'Vina Angelia',
                'email' => 'vina.angelia@maknaonline.com',
                'phone' => '81234567919',
                'address' => 'Jl. Rempoa No. 1111, Tangerang Selatan',
                'position' => 'Documentation Specialist',
                'salary' => 6800000,
                'date_of_birth' => '1992-07-08',
                'date_of_join' => '2021-11-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '2109876543',
                'instagram' => 'vina_angelia_makna',
                'note' => 'Documentation specialist untuk photo & video coordination.',
            ],
            [
                'name' => 'Wawan Setiawan',
                'email' => 'wawan.setiawan@maknaonline.com',
                'phone' => '81234567920',
                'address' => 'Jl. Jagakarsa No. 1212, Jakarta Selatan',
                'position' => 'Setup Crew Leader',
                'salary' => 7000000,
                'date_of_birth' => '1989-04-15',
                'date_of_join' => '2020-11-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '3210987654',
                'instagram' => 'wawan_setiawan_makna',
                'note' => 'Setup crew leader dengan keahlian dalam decoration installation.',
            ],
            [
                'name' => 'Xenia Pratiwi',
                'email' => 'xenia.pratiwi@maknaonline.com',
                'phone' => '81234567921',
                'address' => 'Jl. Cinere No. 1313, Depok',
                'position' => 'Guest Relations',
                'salary' => 6100000,
                'date_of_birth' => '1994-09-03',
                'date_of_join' => '2022-04-05',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '4321098765',
                'instagram' => 'xenia_pratiwi_makna',
                'note' => 'Guest relations specialist untuk VIP dan international guests.',
            ],
            [
                'name' => 'Yoga Pradana',
                'email' => 'yoga.pradana@maknaonline.com',
                'phone' => '81234567922',
                'address' => 'Jl. Lenteng Agung No. 1414, Jakarta Selatan',
                'position' => 'Inventory Manager',
                'salary' => 7500000,
                'date_of_birth' => '1990-12-20',
                'date_of_join' => '2021-01-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '5432109876',
                'instagram' => 'yoga_pradana_makna',
                'note' => 'Inventory manager yang mengelola equipment dan decoration stocks.',
            ],
            [
                'name' => 'Zahra Amelia',
                'email' => 'zahra.amelia@maknaonline.com',
                'phone' => '81234567923',
                'address' => 'Jl. Cibinong No. 1515, Bogor',
                'position' => 'Wedding Planner',
                'salary' => 8500000,
                'date_of_birth' => '1988-05-11',
                'date_of_join' => '2020-07-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '6543210987',
                'instagram' => 'zahra_amelia_makna',
                'note' => 'Senior wedding planner dengan expertise dalam luxury destination weddings.',
            ],
            [
                'name' => 'Arman Hidayat',
                'email' => 'arman.hidayat@maknaonline.com',
                'phone' => '81234567924',
                'address' => 'Jl. Sentul City No. 1616, Bogor',
                'position' => 'Multimedia Designer',
                'salary' => 7200000,
                'date_of_birth' => '1991-08-27',
                'date_of_join' => '2021-06-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '7654321098',
                'instagram' => 'arman_hidayat_makna',
                'note' => 'Multimedia designer untuk wedding invitations dan digital content.',
            ],
            [
                'name' => 'Bella Kusuma',
                'email' => 'bella.kusuma@maknaonline.com',
                'phone' => '81234567925',
                'address' => 'Jl. Depok Raya No. 1717, Depok',
                'position' => 'Budget Analyst',
                'salary' => 7800000,
                'date_of_birth' => '1992-02-14',
                'date_of_join' => '2021-09-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '8765432109',
                'instagram' => 'bella_kusuma_makna',
                'note' => 'Budget analyst yang mengelola cost analysis dan financial planning.',
            ],
            [
                'name' => 'Cahyo Nugroho',
                'email' => 'cahyo.nugroho@maknaonline.com',
                'phone' => '81234567926',
                'address' => 'Jl. Sawangan No. 1818, Depok',
                'position' => 'Venue Specialist',
                'salary' => 6900000,
                'date_of_birth' => '1993-10-06',
                'date_of_join' => '2022-01-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '9876543210',
                'instagram' => 'cahyo_nugroho_makna',
                'note' => 'Venue specialist yang mengelola partnership dengan gedung dan hotel.',
            ],
            [
                'name' => 'Diana Putri',
                'email' => 'diana.putri@maknaonline.com',
                'phone' => '81234567927',
                'address' => 'Jl. Cileungsi No. 1919, Bogor',
                'position' => 'Flower Arrangement Specialist',
                'salary' => 6400000,
                'date_of_birth' => '1994-06-29',
                'date_of_join' => '2022-03-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '1234509876',
                'instagram' => 'diana_putri_makna',
                'note' => 'Flower arrangement specialist dengan keahlian dalam fresh dan artificial flowers.',
            ],
            [
                'name' => 'Edi Suryana',
                'email' => 'edi.suryana@maknaonline.com',
                'phone' => '81234567928',
                'address' => 'Jl. Parung No. 2020, Bogor',
                'position' => 'Equipment Technician',
                'salary' => 6700000,
                'date_of_birth' => '1990-01-10',
                'date_of_join' => '2021-04-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '2345609871',
                'instagram' => 'edi_suryana_makna',
                'note' => 'Equipment technician untuk maintenance sound system dan lighting.',
            ],
            [
                'name' => 'Fani Wulandari',
                'email' => 'fani.wulandari@maknaonline.com',
                'phone' => '81234567929',
                'address' => 'Jl. Gunung Putri No. 2121, Bogor',
                'position' => 'Guest Coordination',
                'salary' => 5900000,
                'date_of_birth' => '1995-05-18',
                'date_of_join' => '2022-06-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '3456709872',
                'instagram' => 'fani_wulandari_makna',
                'note' => 'Guest coordination specialist untuk seating arrangement dan protocol.',
            ],
            [
                'name' => 'Gilang Ramadhan',
                'email' => 'gilang.ramadhan@maknaonline.com',
                'phone' => '81234567930',
                'address' => 'Jl. Citayam No. 2222, Depok',
                'position' => 'Cultural Wedding Specialist',
                'salary' => 8000000,
                'date_of_birth' => '1987-09-25',
                'date_of_join' => '2020-05-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '4567809873',
                'instagram' => 'gilang_ramadhan_makna',
                'note' => 'Cultural wedding specialist dengan expertise dalam adat Jawa, Bali, dan Betawi.',
            ],
            [
                'name' => 'Hesti Wulandari',
                'email' => 'hesti.wulandari@maknaonline.com',
                'phone' => '81234567931',
                'address' => 'Jl. Bojong Gede No. 2323, Bogor',
                'position' => 'Timeline Coordinator',
                'salary' => 6800000,
                'date_of_birth' => '1992-11-12',
                'date_of_join' => '2021-12-05',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '5678909874',
                'instagram' => 'hesti_wulandari_makna',
                'note' => 'Timeline coordinator yang memastikan smooth running day-of wedding.',
            ],
            [
                'name' => 'Ivan Setiawan',
                'email' => 'ivan.setiawan@maknaonline.com',
                'phone' => '81234567932',
                'address' => 'Jl. Cibitung No. 2424, Bekasi',
                'position' => 'Emergency Response',
                'salary' => 6200000,
                'date_of_birth' => '1990-07-04',
                'date_of_join' => '2021-08-25',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '6789009875',
                'instagram' => 'ivan_setiawan_makna',
                'note' => 'Emergency response coordinator untuk handling unexpected situations.',
            ],
            [
                'name' => 'Jessica Tan',
                'email' => 'jessica.tan@maknaonline.com',
                'phone' => '81234567933',
                'address' => 'Jl. Kelapa Gading No. 2525, Jakarta Utara',
                'position' => 'International Wedding Specialist',
                'salary' => 9200000,
                'date_of_birth' => '1988-03-21',
                'date_of_join' => '2020-02-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '7890109876',
                'instagram' => 'jessica_tan_makna',
                'note' => 'International wedding specialist fluent in English, Mandarin, dan Bahasa.',
            ],
            [
                'name' => 'Kevin Wijaya',
                'email' => 'kevin.wijaya@maknaonline.com',
                'phone' => '81234567934',
                'address' => 'Jl. Pluit No. 2626, Jakarta Utara',
                'position' => 'Live Streaming Coordinator',
                'salary' => 7100000,
                'date_of_birth' => '1993-12-07',
                'date_of_join' => '2022-01-05',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '8901209877',
                'instagram' => 'kevin_wijaya_makna',
                'note' => 'Live streaming coordinator untuk virtual wedding dan hybrid events.',
            ],
            [
                'name' => 'Lia Permata',
                'email' => 'lia.permata@maknaonline.com',
                'phone' => '81234567935',
                'address' => 'Jl. Sunter No. 2727, Jakarta Utara',
                'position' => 'Wedding Insurance Specialist',
                'salary' => 7400000,
                'date_of_birth' => '1991-04-23',
                'date_of_join' => '2021-07-10',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '9012309878',
                'instagram' => 'lia_permata_makna',
                'note' => 'Wedding insurance specialist yang mengelola coverage dan risk management.',
            ],
            [
                'name' => 'Monica Sari',
                'email' => 'monica.sari@maknaonline.com',
                'phone' => '81234567936',
                'address' => 'Jl. Kemayoran No. 2828, Jakarta Pusat',
                'position' => 'Honeymoon Coordinator',
                'salary' => 6900000,
                'date_of_birth' => '1994-08-15',
                'date_of_join' => '2022-04-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '1023409879',
                'instagram' => 'monica_sari_makna',
                'note' => 'Honeymoon coordinator yang mengatur travel dan accommodation packages.',
            ],
            [
                'name' => 'Nico Pranoto',
                'email' => 'nico.pranoto@maknaonline.com',
                'phone' => '81234567937',
                'address' => 'Jl. Gambir No. 2929, Jakarta Pusat',
                'position' => 'Registry Coordinator',
                'salary' => 6300000,
                'date_of_birth' => '1992-06-01',
                'date_of_join' => '2021-10-15',
                'date_of_out' => null,
                'bank_name' => 'Bank Central Asia (BCA)',
                'no_rek' => '2134509880',
                'instagram' => 'nico_pranoto_makna',
                'note' => 'Registry coordinator untuk wedding gift registry dan thank you management.',
            ],
            [
                'name' => 'Olivia Kusuma',
                'email' => 'olivia.kusuma@maknaonline.com',
                'phone' => '81234567938',
                'address' => 'Jl. Menteng No. 3030, Jakarta Pusat',
                'position' => 'Sustainability Coordinator',
                'salary' => 7600000,
                'date_of_birth' => '1990-10-28',
                'date_of_join' => '2021-03-01',
                'date_of_out' => null,
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'no_rek' => '3245609881',
                'instagram' => 'olivia_kusuma_makna',
                'note' => 'Sustainability coordinator untuk eco-friendly dan zero-waste weddings.',
            ],
            [
                'name' => 'Patricia Lim',
                'email' => 'patricia.lim@maknaonline.com',
                'phone' => '81234567939',
                'address' => 'Jl. Harmoni No. 3131, Jakarta Pusat',
                'position' => 'Wedding Tech Specialist',
                'salary' => 8300000,
                'date_of_birth' => '1989-02-17',
                'date_of_join' => '2020-11-20',
                'date_of_out' => null,
                'bank_name' => 'Bank Mandiri',
                'no_rek' => '4356709882',
                'instagram' => 'patricia_lim_makna',
                'note' => 'Wedding tech specialist untuk digital integration dan smart wedding solutions.',
            ],
        ];

        foreach ($employees as $employeeData) {
            // Generate slug from name
            $employeeData['slug'] = Str::slug($employeeData['name']);

            // Convert string dates to Carbon instances
            $employeeData['date_of_birth'] = Carbon::parse($employeeData['date_of_birth']);
            $employeeData['date_of_join'] = Carbon::parse($employeeData['date_of_join']);

            if ($employeeData['date_of_out']) {
                $employeeData['date_of_out'] = Carbon::parse($employeeData['date_of_out']);
            }

            // Try to find and assign a user_id (optional)
            $user = User::where('email', $employeeData['email'])->first();
            if ($user) {
                $employeeData['user_id'] = $user->id;
            }

            // Check if employee already exists by email to avoid duplicates
            Employee::firstOrCreate(
                ['email' => $employeeData['email']], // Check by email
                $employeeData // Create with these data if not found
            );
        }

        $this->command->info('✅ EmployeeSeeder completed! Created '.count($employees).' employees (50 total).');
    }
}
