<?php

namespace Database\Seeders;

use App\Models\Prospect;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProspectSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        // Get some users to assign as account managers
        $users = User::all();

        if ($users->isEmpty()) {
            $this->command->error('No users found. Please run UserSeeder first.');

            return;
        }

        $prospects = [
            [
                'name_event' => 'Wedding Andi & Sari',
                'name_cpp' => 'Andi Pratama',
                'name_cpw' => 'Sari Dewi',
                'date_lamaran' => Carbon::now()->addMonths(2)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addDay()->format('Y-m-d'),
                'venue' => 'Hotel Grand Ballroom Jakarta',
                'phone' => '8123456789',
                'address' => 'Jl. Sudirman No. 123, Jakarta Pusat',
                'total_penawaran' => 75000000,
                'notes' => 'Paket lengkap wedding organizer dengan dekorasi mewah dan catering 300 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Budi & Maya',
                'name_cpp' => 'Budi Santoso',
                'name_cpw' => 'Maya Putri',
                'date_lamaran' => Carbon::now()->addMonths(1)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'venue' => 'Gedung Serbaguna Bogor',
                'phone' => '8234567890',
                'address' => 'Jl. Raya Bogor No. 456, Bogor',
                'total_penawaran' => 45000000,
                'notes' => 'Wedding outdoor dengan tema garden party, catering 200 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Dedi & Rina',
                'name_cpp' => 'Dedi Kurniawan',
                'name_cpw' => 'Rina Sari',
                'date_lamaran' => Carbon::now()->addWeeks(3)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(2)->addDays(2)->format('Y-m-d'),
                'venue' => 'Balai Kartini Jakarta',
                'phone' => '8345678901',
                'address' => 'Jl. Gatot Subroto No. 789, Jakarta Selatan',
                'total_penawaran' => 55000000,
                'notes' => 'Tema tradisional Jawa dengan gamelan dan tarian, catering 250 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Eko & Fitri',
                'name_cpp' => 'Eko Prasetyo',
                'name_cpw' => 'Fitri Handayani',
                'date_lamaran' => Carbon::now()->addMonths(1)->addWeeks(2)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'venue' => 'Villa Puncak Resort',
                'phone' => '8456789012',
                'address' => 'Jl. Kemang Raya No. 321, Jakarta Selatan',
                'total_penawaran' => 85000000,
                'notes' => 'Destination wedding di Puncak dengan paket lengkap 2 hari 1 malam, catering 180 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Fajar & Indira',
                'name_cpp' => 'Fajar Nugroho',
                'name_cpw' => 'Indira Salsabila',
                'date_lamaran' => Carbon::now()->addWeeks(6)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(6)->addDay()->format('Y-m-d'),
                'venue' => 'The Ritz Carlton Ballroom',
                'phone' => '8567890123',
                'address' => 'Jl. HR Rasuna Said No. 654, Jakarta',
                'total_penawaran' => 120000000,
                'notes' => 'Wedding mewah dengan tema modern elegant, full decoration, catering premium 400 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Galih & Hana',
                'name_cpp' => 'Galih Ramadhan',
                'name_cpw' => 'Hana Pertiwi',
                'date_lamaran' => Carbon::now()->addMonths(1)->addWeeks(1)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addWeeks(2)->format('Y-m-d'),
                'venue' => 'Grand Sahid Jaya Hotel',
                'phone' => '8678901234',
                'address' => 'Jl. Sudirman Kav. 86, Jakarta Pusat',
                'total_penawaran' => 90000000,
                'notes' => 'Wedding tradisional Sunda dengan paket lengkap, catering 350 pax, live music degung',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Ivan & Julia',
                'name_cpp' => 'Ivan Kurniawan',
                'name_cpw' => 'Julia Maharani',
                'date_lamaran' => Carbon::now()->addWeeks(4)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addWeeks(2)->addDay()->format('Y-m-d'),
                'venue' => 'Mulia Resort Nusa Dua',
                'phone' => '8789012345',
                'address' => 'Jl. Melawai Raya No. 123, Jakarta Selatan',
                'total_penawaran' => 150000000,
                'notes' => 'Destination wedding di Bali dengan paket 3 hari 2 malam, catering 200 pax, full vendor',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Khalil & Lina',
                'name_cpp' => 'Khalil Ahmad',
                'name_cpw' => 'Lina Safitri',
                'date_lamaran' => Carbon::now()->addMonths(2)->addWeeks(1)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addWeeks(1)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addWeeks(1)->format('Y-m-d'),
                'venue' => 'Masjid Istiqlal & JCC Senayan',
                'phone' => '8890123456',
                'address' => 'Jl. Tebet Raya No. 789, Jakarta Selatan',
                'total_penawaran' => 65000000,
                'notes' => 'Wedding islami dengan akad di Masjid Istiqlal, resepsi di JCC, catering halal 400 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Made & Ni Kadek',
                'name_cpp' => 'Made Wirawan',
                'name_cpw' => 'Ni Kadek Sari',
                'date_lamaran' => Carbon::now()->addWeeks(2)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'venue' => 'Pura Tanah Lot & Bali Beach Resort',
                'phone' => '8901234567',
                'address' => 'Jl. Denpasar-Gilimanuk, Tabanan, Bali',
                'total_penawaran' => 110000000,
                'notes' => 'Wedding adat Bali dengan upacara lengkap, venue di pantai, catering tradisional 300 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Nurdin & Olivia',
                'name_cpp' => 'Nurdin Hasibuan',
                'name_cpw' => 'Olivia Tambunan',
                'date_lamaran' => Carbon::now()->addMonths(1)->addDays(10)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addDays(15)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addDays(16)->format('Y-m-d'),
                'venue' => 'Gedung Graha Sabha Pramana UGM',
                'phone' => '8012345678',
                'address' => 'Jl. Sosio Humaniora, Bulaksumur, Yogyakarta',
                'total_penawaran' => 70000000,
                'notes' => 'Wedding di Yogyakarta dengan tema Jawa-Batak, catering gudeg dan babi panggang, 280 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Putra & Queen',
                'name_cpp' => 'Putra Mahendra',
                'name_cpw' => 'Queen Elisabeth',
                'date_lamaran' => Carbon::now()->addWeeks(5)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(6)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(6)->addWeeks(2)->format('Y-m-d'),
                'venue' => 'Shangri-La Hotel Surabaya',
                'phone' => '8123456789',
                'address' => 'Jl. Mayjen Sungkono No. 120, Surabaya',
                'total_penawaran' => 95000000,
                'notes' => 'Wedding international style dengan tema gold & white, catering fusion 320 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Rizki & Sinta',
                'name_cpp' => 'Rizki Pratama',
                'name_cpw' => 'Sinta Dewi',
                'date_lamaran' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(2)->addDays(10)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(2)->addDays(11)->format('Y-m-d'),
                'venue' => 'Taman Mini Indonesia Indah',
                'phone' => '8234567890',
                'address' => 'Jl. Raya Taman Mini, Jakarta Timur',
                'total_penawaran' => 80000000,
                'notes' => 'Wedding outdoor di TMII dengan tema nusantara, catering dari berbagai daerah, 350 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Satrio & Tika',
                'name_cpp' => 'Satrio Wibowo',
                'name_cpw' => 'Tika Sari',
                'date_lamaran' => Carbon::now()->addMonths(1)->addWeeks(3)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addWeeks(1)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addWeeks(1)->addDay()->format('Y-m-d'),
                'venue' => 'Istana Bogor & Kebun Raya Bogor',
                'phone' => '8345678901',
                'address' => 'Jl. Ir. H. Djuanda No. 13, Bogor',
                'total_penawaran' => 100000000,
                'notes' => 'Wedding garden party di Kebun Raya Bogor, tema natural elegant, catering organic 250 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Umar & Vera',
                'name_cpp' => 'Umar Faruq',
                'name_cpw' => 'Vera Anggraini',
                'date_lamaran' => Carbon::now()->addWeeks(7)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addWeeks(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addWeeks(3)->format('Y-m-d'),
                'venue' => 'Hotel Indonesia Kempinski',
                'phone' => '8456789012',
                'address' => 'Jl. MH Thamrin No. 1, Jakarta Pusat',
                'total_penawaran' => 135000000,
                'notes' => 'Wedding mewah di ballroom HI dengan tema royal blue, catering fine dining 380 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Wahyu & Xenia',
                'name_cpp' => 'Wahyu Hidayat',
                'name_cpw' => 'Xenia Putri',
                'date_lamaran' => Carbon::now()->addMonths(2)->addWeeks(2)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(6)->addDay()->format('Y-m-d'),
                'venue' => 'Fairmont Jakarta & Ancol Beach',
                'phone' => '8567890123',
                'address' => 'Jl. Asia Afrika Senayan, Jakarta Pusat',
                'total_penawaran' => 125000000,
                'notes' => 'Wedding dengan after party di pantai Ancol, tema sunset beach, catering seafood 300 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Yoga & Zahra',
                'name_cpp' => 'Yoga Pratama',
                'name_cpw' => 'Zahra Amelia',
                'date_lamaran' => Carbon::now()->addWeeks(8)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(7)->addDay()->format('Y-m-d'),
                'venue' => 'Trans Luxury Hotel Bandung',
                'phone' => '8678901234',
                'address' => 'Jl. Gatot Subroto No. 289, Bandung',
                'total_penawaran' => 88000000,
                'notes' => 'Wedding di Bandung dengan tema rustic vintage, catering Sunda modern 280 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Arief & Bella',
                'name_cpp' => 'Arief Rachman',
                'name_cpw' => 'Bella Safira',
                'date_lamaran' => Carbon::now()->addDays(25)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addDays(5)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addDays(6)->format('Y-m-d'),
                'venue' => 'Pullman Jakarta Central Park',
                'phone' => '8789012345',
                'address' => 'Jl. Letjen S. Parman Kav. 28, Jakarta Barat',
                'total_penawaran' => 105000000,
                'notes' => 'Wedding modern minimalist dengan tema monochrome, catering international 320 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Chandra & Diana',
                'name_cpp' => 'Chandra Wijaya',
                'name_cpw' => 'Diana Maharani',
                'date_lamaran' => Carbon::now()->addMonths(1)->addDays(15)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addDays(20)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addDays(21)->format('Y-m-d'),
                'venue' => 'Hotel Borobudur Jakarta',
                'phone' => '8890123456',
                'address' => 'Jl. Lapangan Banteng Selatan, Jakarta Pusat',
                'total_penawaran' => 115000000,
                'notes' => 'Wedding klasik elegan dengan dekorasi bunga fresh, catering fine dining 350 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Eko & Fatma',
                'name_cpp' => 'Eko Saputra',
                'name_cpw' => 'Fatma Sari',
                'date_lamaran' => Carbon::now()->addWeeks(6)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addWeeks(2)->format('Y-m-d'),
                'venue' => 'JW Marriott Hotel Medan',
                'phone' => '8901234567',
                'address' => 'Jl. Putri Hijau No. 10, Medan',
                'total_penawaran' => 78000000,
                'notes' => 'Wedding di Medan dengan tema tradisional Batak, catering authentic 300 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Farid & Gita',
                'name_cpp' => 'Farid Hakim',
                'name_cpw' => 'Gita Permata',
                'date_lamaran' => Carbon::now()->addDays(30)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(2)->addWeeks(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(2)->addWeeks(3)->addDay()->format('Y-m-d'),
                'venue' => 'Crowne Plaza Semarang',
                'phone' => '8012345678',
                'address' => 'Jl. Pemuda No. 118, Semarang',
                'total_penawaran' => 72000000,
                'notes' => 'Wedding di Semarang dengan tema navy gold, catering Jawa tengah 260 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Hendra & Ira',
                'name_cpp' => 'Hendra Gunawan',
                'name_cpw' => 'Ira Novita',
                'date_lamaran' => Carbon::now()->addMonths(1)->addWeeks(4)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(6)->addDays(10)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(6)->addDays(11)->format('Y-m-d'),
                'venue' => 'Hyatt Regency Yogyakarta',
                'phone' => '8123456789',
                'address' => 'Jl. Palagan Tentara Pelajar, Yogyakarta',
                'total_penawaran' => 82000000,
                'notes' => 'Wedding di Yogya dengan tema royal Javanese, catering royal 290 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Indra & Julita',
                'name_cpp' => 'Indra Kusuma',
                'name_cpw' => 'Julita Sari',
                'date_lamaran' => Carbon::now()->addWeeks(9)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'venue' => 'The Westin Resort Nusa Dua',
                'phone' => '8234567890',
                'address' => 'Jl. Raya Nusa Dua Selatan, Bali',
                'total_penawaran' => 165000000,
                'notes' => 'Destination wedding di Bali dengan paket 4 hari 3 malam, tema tropical luxury, 180 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Kevin & Lestari',
                'name_cpp' => 'Kevin Tan',
                'name_cpw' => 'Lestari Wulan',
                'date_lamaran' => Carbon::now()->addDays(45)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addWeeks(1)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addWeeks(1)->format('Y-m-d'),
                'venue' => 'Mandarin Oriental Jakarta',
                'phone' => '8345678901',
                'address' => 'Jl. MH Thamrin, Jakarta Pusat',
                'total_penawaran' => 140000000,
                'notes' => 'Wedding luxury dengan tema red gold Chinese modern, catering fusion 380 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Mario & Nina',
                'name_cpp' => 'Mario Siahaan',
                'name_cpw' => 'Nina Angelina',
                'date_lamaran' => Carbon::now()->addMonths(2)->addDays(5)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addDays(8)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addDays(9)->format('Y-m-d'),
                'venue' => 'Ayana Resort Bali',
                'phone' => '8456789012',
                'address' => 'Jl. Karang Mas Sejahtera, Bali',
                'total_penawaran' => 175000000,
                'notes' => 'Cliff top wedding di Ayana dengan sunset ceremony, tema bohemian chic, 200 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Oscar & Putri',
                'name_cpp' => 'Oscar Pratama',
                'name_cpw' => 'Putri Maharani',
                'date_lamaran' => Carbon::now()->addWeeks(10)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(7)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(7)->addWeeks(2)->format('Y-m-d'),
                'venue' => 'Four Seasons Hotel Jakarta',
                'phone' => '8567890123',
                'address' => 'Jl. HR Rasuna Said Kav. C-15, Jakarta',
                'total_penawaran' => 155000000,
                'notes' => 'Wedding ultra luxury dengan tema crystal white, catering molekuler 300 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Qori & Ratih',
                'name_cpp' => 'Qori Rahman',
                'name_cpw' => 'Ratih Kusuma',
                'date_lamaran' => Carbon::now()->addDays(18)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(2)->addDays(22)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(2)->addDays(23)->format('Y-m-d'),
                'venue' => 'Grand Hyatt Jakarta',
                'phone' => '8678901234',
                'address' => 'Jl. MH Thamrin Kav. 28-30, Jakarta',
                'total_penawaran' => 125000000,
                'notes' => 'Wedding contemporary dengan tema emerald green, catering international 350 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Ricky & Silvia',
                'name_cpp' => 'Ricky Handoko',
                'name_cpw' => 'Silvia Tan',
                'date_lamaran' => Carbon::now()->addMonths(1)->addDays(8)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addWeeks(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addWeeks(3)->addDay()->format('Y-m-d'),
                'venue' => 'InterContinental Jakarta Pondok Indah',
                'phone' => '8789012345',
                'address' => 'Jl. Metro Pondok Indah, Jakarta Selatan',
                'total_penawaran' => 98000000,
                'notes' => 'Wedding garden party dengan tema peach coral, catering mediteranian 320 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Teguh & Ulfa',
                'name_cpp' => 'Teguh Santoso',
                'name_cpw' => 'Ulfa Rahmawati',
                'date_lamaran' => Carbon::now()->addWeeks(7)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(6)->addWeeks(1)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(6)->addWeeks(1)->format('Y-m-d'),
                'venue' => 'Swiss-Belhotel Rainforest Kuta',
                'phone' => '8890123456',
                'address' => 'Jl. Kartika Plaza, Kuta, Bali',
                'total_penawaran' => 92000000,
                'notes' => 'Beach wedding di Kuta dengan tema tropical paradise, catering seafood BBQ 250 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Victor & Winda',
                'name_cpp' => 'Victor Halim',
                'name_cpw' => 'Winda Sari',
                'date_lamaran' => Carbon::now()->addDays(35)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addDays(12)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addDays(13)->format('Y-m-d'),
                'venue' => 'The Langham Jakarta',
                'phone' => '8901234567',
                'address' => 'District 8 Senopati, Jakarta Selatan',
                'total_penawaran' => 135000000,
                'notes' => 'Wedding modern sophisticated dengan tema black gold, catering fine dining 400 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Willy & Yenny',
                'name_cpp' => 'Willy Setiawan',
                'name_cpw' => 'Yenny Lim',
                'date_lamaran' => Carbon::now()->addMonths(2)->addWeeks(1)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addDays(15)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addDays(16)->format('Y-m-d'),
                'venue' => 'Conrad Bali',
                'phone' => '8012345678',
                'address' => 'Jl. Pratama 168, Tanjung Benoa, Bali',
                'total_penawaran' => 158000000,
                'notes' => 'Beachfront wedding dengan Chinese tea ceremony, tema ivory blush, 220 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Zaki & Amira',
                'name_cpp' => 'Zaki Firmansyah',
                'name_cpw' => 'Amira Handayani',
                'date_lamaran' => Carbon::now()->addWeeks(11)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(8)->addWeeks(1)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(8)->addWeeks(1)->format('Y-m-d'),
                'venue' => 'Alila Villas Uluwatu',
                'phone' => '8123456789',
                'address' => 'Jl. Belimbing Sari, Uluwatu, Bali',
                'total_penawaran' => 180000000,
                'notes' => 'Cliff wedding di Uluwatu dengan tema sunset modern, intimate dinner 150 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Bayu & Cynthia',
                'name_cpp' => 'Bayu Nugroho',
                'name_cpw' => 'Cynthia Wijaya',
                'date_lamaran' => Carbon::now()->addDays(28)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(2)->addWeeks(4)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(2)->addWeeks(4)->addDay()->format('Y-m-d'),
                'venue' => 'Shangri-La Boracay Resort',
                'phone' => '8234567890',
                'address' => 'Station 1, Boracay Island, Philippines',
                'total_penawaran' => 200000000,
                'notes' => 'International destination wedding di Boracay, tema white beach, 180 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Denny & Evelyn',
                'name_cpp' => 'Denny Kurniawan',
                'name_cpw' => 'Evelyn Tania',
                'date_lamaran' => Carbon::now()->addMonths(1)->addDays(12)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addDays(18)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addDays(19)->format('Y-m-d'),
                'venue' => 'Hotel Tugu Lombok',
                'phone' => '8345678901',
                'address' => 'Jl. Pantai Sire, Lombok',
                'total_penawaran' => 145000000,
                'notes' => 'Traditional Lombok wedding dengan tema Sasak culture, catering authentic 280 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Ferry & Grace',
                'name_cpp' => 'Ferry Gunawan',
                'name_cpw' => 'Grace Angelia',
                'date_lamaran' => Carbon::now()->addWeeks(5)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addWeeks(4)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addWeeks(4)->format('Y-m-d'),
                'venue' => 'Raffles Hotel Jakarta',
                'phone' => '8456789012',
                'address' => 'Jl. Prof. Dr. Satrio Kav. 3-5, Jakarta',
                'total_penawaran' => 168000000,
                'notes' => 'Heritage luxury wedding dengan tema vintage glamour, catering classic 360 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Haris & Indah',
                'name_cpp' => 'Haris Maulana',
                'name_cpw' => 'Indah Permatasari',
                'date_lamaran' => Carbon::now()->addDays(40)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addDays(8)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addDays(9)->format('Y-m-d'),
                'venue' => 'Sheraton Bandung Hotel',
                'phone' => '8567890123',
                'address' => 'Jl. Ir. H. Djuanda No. 390, Bandung',
                'total_penawaran' => 85000000,
                'notes' => 'Wedding di Bandung dengan tema pink dusty rose, catering Sunda fusion 310 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Irfan & Jasmine',
                'name_cpp' => 'Irfan Hakim',
                'name_cpw' => 'Jasmine Putri',
                'date_lamaran' => Carbon::now()->addMonths(1)->addWeeks(2)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addWeeks(4)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(4)->addWeeks(4)->addDay()->format('Y-m-d'),
                'venue' => 'W Retreat & Spa Bali',
                'phone' => '8678901234',
                'address' => 'Jl. Petitenget, Seminyak, Bali',
                'total_penawaran' => 162000000,
                'notes' => 'Modern beach wedding dengan tema bohemian luxury, sunset reception 190 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Joko & Kartika',
                'name_cpp' => 'Joko Widodo',
                'name_cpw' => 'Kartika Sari',
                'date_lamaran' => Carbon::now()->addWeeks(12)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(9)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(9)->format('Y-m-d'),
                'venue' => 'Royal Ambarrukmo Yogyakarta',
                'phone' => '8789012345',
                'address' => 'Jl. Laksda Adisucipto No. 81, Yogyakarta',
                'total_penawaran' => 76000000,
                'notes' => 'Traditional Javanese wedding dengan gamelan orchestra, tema bronze gold 290 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Lucky & Maya',
                'name_cpp' => 'Lucky Handoko',
                'name_cpw' => 'Maya Sari',
                'date_lamaran' => Carbon::now()->addDays(50)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addWeeks(2)->addDay()->format('Y-m-d'),
                'venue' => 'Hotel Santika Premiere Slipi',
                'phone' => '8890123456',
                'address' => 'Jl. Letjen S. Parman Kav. 47, Jakarta Barat',
                'total_penawaran' => 69000000,
                'notes' => 'Intimate wedding dengan tema sage green, catering buffet international 240 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Nanda & Olivia',
                'name_cpp' => 'Nanda Prakoso',
                'name_cpw' => 'Olivia Lestari',
                'date_lamaran' => Carbon::now()->addMonths(2)->addDays(12)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addDays(25)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addDays(26)->format('Y-m-d'),
                'venue' => 'The Stones Hotel Legian',
                'phone' => '8901234567',
                'address' => 'Jl. Raya Pantai Kuta, Legian, Bali',
                'total_penawaran' => 142000000,
                'notes' => 'Beachside wedding dengan tema tropical modern, fire dance performance 260 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Peter & Quin',
                'name_cpp' => 'Peter Halim',
                'name_cpw' => 'Quin Felicia',
                'date_lamaran' => Carbon::now()->addWeeks(8)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(7)->addDays(5)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(7)->addDays(6)->format('Y-m-d'),
                'venue' => 'St. Regis Bali Resort',
                'phone' => '8012345678',
                'address' => 'Strand Beach, Nusa Dua, Bali',
                'total_penawaran' => 195000000,
                'notes' => 'Ultra luxury beachfront wedding dengan tema white platinum, butler service 200 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Rahmat & Siska',
                'name_cpp' => 'Rahmat Hidayat',
                'name_cpw' => 'Siska Dewi',
                'date_lamaran' => Carbon::now()->addDays(22)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(2)->addDays(28)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(2)->addDays(29)->format('Y-m-d'),
                'venue' => 'Harris Hotel Kelapa Gading',
                'phone' => '8123456789',
                'address' => 'Jl. Boulevard Barat, Kelapa Gading, Jakarta',
                'total_penawaran' => 58000000,
                'notes' => 'Simple elegant wedding dengan tema purple lavender, catering prasmanan 220 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Tommy & Utami',
                'name_cpp' => 'Tommy Wijaya',
                'name_cpw' => 'Utami Sari',
                'date_lamaran' => Carbon::now()->addMonths(1)->addDays(20)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(4)->addDays(30)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'venue' => 'Crowne Plaza Bandung',
                'phone' => '8234567890',
                'address' => 'Jl. Lembong No. 19, Bandung',
                'total_penawaran' => 81000000,
                'notes' => 'Wedding di Bandung dengan tema blush pink, outdoor ceremony 270 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Vicky & Wulan',
                'name_cpp' => 'Vicky Pratama',
                'name_cpw' => 'Wulan Dari',
                'date_lamaran' => Carbon::now()->addWeeks(13)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(10)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(10)->addDay()->format('Y-m-d'),
                'venue' => 'Padma Resort Ubud',
                'phone' => '8345678901',
                'address' => 'Jl. Raya Payangan, Ubud, Bali',
                'total_penawaran' => 152000000,
                'notes' => 'Jungle wedding di Ubud dengan tema natural rustic, organic catering 170 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Yoga & Yuli',
                'name_cpp' => 'Yoga Aditya',
                'name_cpw' => 'Yuli Astari',
                'date_lamaran' => Carbon::now()->addDays(55)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->addWeeks(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addWeeks(3)->addDay()->format('Y-m-d'),
                'venue' => 'The Phoenix Hotel Yogyakarta',
                'phone' => '8456789012',
                'address' => 'Jl. Jenderal Sudirman No. 9, Yogyakarta',
                'total_penawaran' => 74000000,
                'notes' => 'Heritage building wedding dengan tema colonial vintage, traditional dance 250 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Zulfikar & Annisa',
                'name_cpp' => 'Zulfikar Rahman',
                'name_cpw' => 'Annisa Fitri',
                'date_lamaran' => Carbon::now()->addMonths(2)->addWeeks(3)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(6)->addWeeks(2)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(6)->addWeeks(2)->format('Y-m-d'),
                'venue' => 'Hotel Aryaduta Jakarta',
                'phone' => '8567890123',
                'address' => 'Jl. Prapatan Raya No. 44-48, Jakarta',
                'total_penawaran' => 93000000,
                'notes' => 'Islamic wedding dengan tema green emerald, halal catering middle eastern 330 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Adrian & Bella',
                'name_cpp' => 'Adrian Liem',
                'name_cpw' => 'Bella Santosa',
                'date_lamaran' => Carbon::now()->addWeeks(14)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(11)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(11)->format('Y-m-d'),
                'venue' => 'AYANA Komodo Resort',
                'phone' => '8678901234',
                'address' => 'Waecicu Beach, Labuan Bajo, Flores',
                'total_penawaran' => 220000000,
                'notes' => 'Exclusive island wedding di Komodo dengan yacht ceremony, tema ocean blue 120 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Christian & Diana',
                'name_cpp' => 'Christian Budiman',
                'name_cpw' => 'Diana Kusuma',
                'date_lamaran' => Carbon::now()->addDays(32)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(3)->addDay()->format('Y-m-d'),
                'venue' => 'JW Marriott Surabaya',
                'phone' => '8789012345',
                'address' => 'Jl. Embong Malang No. 85-89, Surabaya',
                'total_penawaran' => 96000000,
                'notes' => 'Modern church wedding dengan tema burgundy gold, live orchestra 340 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Edwin & Fiona',
                'name_cpp' => 'Edwin Tanujaya',
                'name_cpw' => 'Fiona Setiawan',
                'date_lamaran' => Carbon::now()->addMonths(1)->addDays(25)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(5)->addWeeks(1)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(5)->addWeeks(1)->addDay()->format('Y-m-d'),
                'venue' => 'The Mulia Bali',
                'phone' => '8890123456',
                'address' => 'Jl. Raya Nusa Dua Selatan, Bali',
                'total_penawaran' => 210000000,
                'notes' => 'Beachfront luxury wedding dengan helicopter arrival, tema crystal white 160 pax',
                'user_id' => $users->random()->id,
            ],
            [
                'name_event' => 'Wedding Gilang & Hesti',
                'name_cpp' => 'Gilang Ramadhan',
                'name_cpw' => 'Hesti Wulandari',
                'date_lamaran' => Carbon::now()->addWeeks(15)->format('Y-m-d'),
                'date_akad' => Carbon::now()->addMonths(12)->format('Y-m-d'),
                'date_resepsi' => Carbon::now()->addMonths(12)->format('Y-m-d'),
                'venue' => 'Plataran Menteng Jakarta',
                'phone' => '8901234567',
                'address' => 'Jl. HOS Cokroaminoto No. 31, Jakarta',
                'total_penawaran' => 87000000,
                'notes' => 'Heritage wedding di Menteng dengan tema classic elegant, live jazz 280 pax',
                'user_id' => $users->random()->id,
            ],
        ];

        foreach ($prospects as $prospectData) {
            Prospect::firstOrCreate(
                [
                    'name_event' => $prospectData['name_event'],
                    'name_cpp' => $prospectData['name_cpp'],
                    'name_cpw' => $prospectData['name_cpw'],
                ],
                $prospectData
            );
        }

        $this->command->info('50 prospects created successfully!');
    }
}
