<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Vendor;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        // Get categories to assign to vendors
        $categories = Category::all();

        if ($categories->isEmpty()) {
            $this->command->error('No categories found. Please run CategorySeeder first or create categories manually.');

            return;
        }

        $vendors = [
            [
                'name' => 'Dekorasi Mewah Jakarta',
                'slug' => 'dekorasi-mewah-jakarta',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Ibu Sari Dewi',
                'phone' => '8123456789',
                'address' => 'Jl. Kemang Raya No. 123, Jakarta Selatan',
                'description' => '<p>Spesialis dekorasi wedding mewah dengan pengalaman 10+ tahun. Melayani dekorasi pelaminan, backdrop, bunga, lighting, dan tata ruang untuk acara pernikahan kelas premium.</p><p><strong>Keunggulan:</strong></p><ul><li>Tim kreatif berpengalaman</li><li>Dekorasi custom sesuai tema</li><li>Peralatan lengkap dan modern</li><li>Konsultasi gratis</li></ul>',
                'harga_publish' => 15000000,
                'harga_vendor' => 12000000,
                'bank_name' => 'BCA',
                'bank_account' => '1234567890',
                'account_holder' => 'Sari Dewi Decoration',
            ],
            [
                'name' => 'Catering Premium Bogor',
                'slug' => 'catering-premium-bogor',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Bapak Ahmad Rizki',
                'phone' => '8234567890',
                'address' => 'Jl. Raya Bogor No. 456, Bogor',
                'description' => '<p>Layanan catering premium untuk wedding dengan menu Indonesia dan Internasional. Melayani berbagai paket sesuai budget dengan kualitas rasa terjamin.</p><p><strong>Paket Tersedia:</strong></p><ul><li>Paket A: 200-300 pax</li><li>Paket B: 300-500 pax</li><li>Paket C: 500+ pax</li><li>Custom menu tersedia</li></ul>',
                'harga_publish' => 8500000,
                'harga_vendor' => 7000000,
                'bank_name' => 'Mandiri',
                'bank_account' => '2345678901',
                'account_holder' => 'Ahmad Rizki Catering',
            ],
            [
                'name' => 'Foto & Video Cinematic',
                'slug' => 'foto-video-cinematic',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Dedi Photographer',
                'phone' => '8345678901',
                'address' => 'Jl. Sudirman No. 789, Jakarta Pusat',
                'description' => '<p>Jasa foto dan video wedding dengan gaya cinematic dan artistic. Menggunakan peralatan profesional dan tim kreatif berpengalaman untuk mengabadikan momen spesial Anda.</p><p><strong>Paket Include:</strong></p><ul><li>Pre-wedding photoshoot</li><li>Wedding day documentation</li><li>Cinematic video</li><li>Album foto premium</li><li>Raw files & edited photos</li></ul>',
                'harga_publish' => 12000000,
                'harga_vendor' => 9500000,
                'bank_name' => 'BRI',
                'bank_account' => '3456789012',
                'account_holder' => 'Dedi Cinematic Studio',
            ],
            [
                'name' => 'Soundsystem Pro Jakarta',
                'slug' => 'soundsystem-pro-jakarta',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Eko Saputra',
                'phone' => '8456789012',
                'address' => 'Jl. Gatot Subroto No. 321, Jakarta Selatan',
                'description' => '<p>Penyedia soundsystem profesional untuk wedding dengan kualitas audio jernih dan peralatan lengkap. Melayani indoor dan outdoor event.</p><p><strong>Peralatan:</strong></p><ul><li>Speaker line array profesional</li><li>Mixing console digital</li><li>Microphone wireless premium</li><li>Lighting system</li><li>Operator berpengalaman</li></ul>',
                'harga_publish' => 5500000,
                'harga_vendor' => 4200000,
                'bank_name' => 'BNI',
                'bank_account' => '4567890123',
                'account_holder' => 'Eko Audio Visual',
            ],
            [
                'name' => 'Make Up Artist Professional',
                'slug' => 'make-up-artist-professional',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Fitri Make Up',
                'phone' => '8567890123',
                'address' => 'Jl. Kemang Selatan No. 654, Jakarta',
                'description' => '<p>Make up artist profesional untuk pengantin dengan berbagai gaya dari tradisional hingga modern. Berpengalaman 8+ tahun dengan sertifikat internasional.</p><p><strong>Layanan:</strong></p><ul><li>Make up pengantin (akad & resepsi)</li><li>Hair styling</li><li>Make up keluarga</li><li>Trial make up</li><li>Touch up selama acara</li></ul>',
                'harga_publish' => 3500000,
                'harga_vendor' => 2800000,
                'bank_name' => 'CIMB Niaga',
                'bank_account' => '5678901234',
                'account_holder' => 'Fitri Maharani',
            ],
            [
                'name' => 'Wedding Car Rental Luxury',
                'slug' => 'wedding-car-rental-luxury',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Indra Mobil',
                'phone' => '8678901234',
                'address' => 'Jl. HR Rasuna Said No. 987, Jakarta',
                'description' => '<p>Rental mobil mewah untuk pengantin dengan koleksi lengkap dari sedan premium hingga sports car. Semua unit terawat dan dilengkapi dekorasi wedding.</p><p><strong>Armada:</strong></p><ul><li>Mercedes Benz S-Class</li><li>BMW 7 Series</li><li>Audi A8</li><li>Rolls Royce (premium)</li><li>Bentley (premium)</li></ul>',
                'harga_publish' => 2500000,
                'harga_vendor' => 2000000,
                'bank_name' => 'Danamon',
                'bank_account' => '6789012345',
                'account_holder' => 'Indra Luxury Car',
            ],
            [
                'name' => 'Entertainment Wedding Organizer',
                'slug' => 'entertainment-wedding-organizer',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Fajar Entertainment',
                'phone' => '8789012345',
                'address' => 'Jl. Senopati No. 159, Jakarta Selatan',
                'description' => '<p>Penyedia entertainment lengkap untuk wedding meliputi MC profesional, band, dancer, dan pertunjukan tradisional. Berpengalaman menangani wedding skala besar.</p><p><strong>Paket Entertainment:</strong></p><ul><li>MC profesional bilingual</li><li>Live band & acoustic</li><li>Traditional dance</li><li>Lighting show</li><li>Special effects</li></ul>',
                'harga_publish' => 7500000,
                'harga_vendor' => 6200000,
                'bank_name' => 'Permata',
                'bank_account' => '7890123456',
                'account_holder' => 'Fajar Media Entertainment',
            ],
            [
                'name' => 'Venue Ballroom Grand',
                'slug' => 'venue-ballroom-grand',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Dewi Sartika',
                'phone' => '8890123456',
                'address' => 'Jl. Thamrin No. 88, Jakarta Pusat',
                'description' => '<p>Ballroom mewah dengan kapasitas 500-1000 tamu. Dilengkapi dengan fasilitas modern dan desain interior elegan untuk wedding reception eksklusif.</p><p><strong>Fasilitas:</strong></p><ul><li>Ballroom ber-AC central</li><li>Stage professional</li><li>Parking area luas</li><li>Bridal room</li><li>Catering area</li></ul>',
                'harga_publish' => 25000000,
                'harga_vendor' => 20000000,
                'bank_name' => 'BCA',
                'bank_account' => '8901234567',
                'account_holder' => 'Grand Ballroom Jakarta',
            ],
            [
                'name' => 'Florist Wedding Specialist',
                'slug' => 'florist-wedding-specialist',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Sinta Bunga',
                'phone' => '8901234567',
                'address' => 'Jl. Melawai No. 234, Jakarta Selatan',
                'description' => '<p>Spesialis rangkaian bunga wedding dengan berbagai pilihan bunga fresh import dan lokal. Melayani bouquet, corsage, dan dekorasi bunga venue.</p><p><strong>Layanan:</strong></p><ul><li>Bridal bouquet</li><li>Boutonniere</li><li>Centerpiece</li><li>Dekorasi altar</li><li>Petal toss</li></ul>',
                'harga_publish' => 4500000,
                'harga_vendor' => 3600000,
                'bank_name' => 'Mandiri',
                'bank_account' => '9012345678',
                'account_holder' => 'Sinta Flower Shop',
            ],
            [
                'name' => 'Lighting Design Pro',
                'slug' => 'lighting-design-pro',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Agus Lighting',
                'phone' => '8012345678',
                'address' => 'Jl. Casablanca No. 567, Jakarta Selatan',
                'description' => '<p>Jasa lighting design profesional untuk wedding dengan berbagai efek dramatic dan romantic. Menggunakan teknologi LED terbaru dan DMX control.</p><p><strong>Paket Lighting:</strong></p><ul><li>Uplighting venue</li><li>Spotlighting couple</li><li>Dancing light effects</li><li>Romantic ambience</li><li>Color wash systems</li></ul>',
                'harga_publish' => 6500000,
                'harga_vendor' => 5200000,
                'bank_name' => 'BRI',
                'bank_account' => '0123456789',
                'account_holder' => 'Agus Lighting Design',
            ],
            [
                'name' => 'Wedding Cake Designer',
                'slug' => 'wedding-cake-designer',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Chef Miranda',
                'phone' => '8123456780',
                'address' => 'Jl. Pondok Indah No. 890, Jakarta Selatan',
                'description' => '<p>Designer kue pengantin custom dengan rasa premium dan desain artistic. Spesialis multi-tier cake dengan berbagai flavor dan dekorasi fondant.</p><p><strong>Specialty:</strong></p><ul><li>Custom design cake</li><li>Premium ingredients</li><li>Multiple flavors</li><li>Sugar art decoration</li><li>Cake cutting ceremony</li></ul>',
                'harga_publish' => 3500000,
                'harga_vendor' => 2800000,
                'bank_name' => 'BNI',
                'bank_account' => '1234567801',
                'account_holder' => 'Miranda Cake Studio',
            ],
            [
                'name' => 'Traditional Gamelan Group',
                'slug' => 'traditional-gamelan-group',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Pak Slamet',
                'phone' => '8234567801',
                'address' => 'Jl. Yogyakarta No. 123, Yogyakarta',
                'description' => '<p>Grup gamelan tradisional Jawa untuk upacara pernikahan adat. Berpengalaman dalam berbagai ceremonial wedding Jawa dan Sunda dengan instrumen lengkap.</p><p><strong>Repertoire:</strong></p><ul><li>Lagu wedding tradisional</li><li>Ceremonial music</li><li>Instrumen gamelan lengkap</li><li>Penari tradisional</li><li>Costume traditional</li></ul>',
                'harga_publish' => 4000000,
                'harga_vendor' => 3200000,
                'bank_name' => 'BCA',
                'bank_account' => '2345678012',
                'account_holder' => 'Slamet Gamelan Group',
            ],
            [
                'name' => 'Invitation Card Designer',
                'slug' => 'invitation-card-designer',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Rina Design',
                'phone' => '8345678012',
                'address' => 'Jl. Cipete No. 456, Jakarta Selatan',
                'description' => '<p>Designer undangan pernikahan custom dengan berbagai material premium dan teknik printing modern. Melayani dari konsep design hingga finishing.</p><p><strong>Material Available:</strong></p><ul><li>Premium paper selection</li><li>Embossing & foil printing</li><li>Laser cut design</li><li>Hardcover invitation</li><li>Digital invitation</li></ul>',
                'harga_publish' => 2500000,
                'harga_vendor' => 2000000,
                'bank_name' => 'Mandiri',
                'bank_account' => '3456780123',
                'account_holder' => 'Rina Creative Design',
            ],
            [
                'name' => 'Wedding Planner Consultant',
                'slug' => 'wedding-planner-consultant',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Ibu Ratna',
                'phone' => '8456780123',
                'address' => 'Jl. Kuningan No. 789, Jakarta Selatan',
                'description' => '<p>Wedding planner profesional dengan pengalaman 15+ tahun. Melayani full planning service dari konsep hingga eksekusi dengan timeline management yang detail.</p><p><strong>Services:</strong></p><ul><li>Full wedding planning</li><li>Vendor coordination</li><li>Budget management</li><li>Timeline execution</li><li>Day-of coordination</li></ul>',
                'harga_publish' => 12000000,
                'harga_vendor' => 9500000,
                'bank_name' => 'BRI',
                'bank_account' => '4567801234',
                'account_holder' => 'Ratna Wedding Consultant',
            ],
            [
                'name' => 'Henna Artist Traditional',
                'slug' => 'henna-artist-traditional',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Fatimah Henna',
                'phone' => '8567801234',
                'address' => 'Jl. Kemayoran No. 321, Jakarta Pusat',
                'description' => '<p>Henna artist profesional untuk pengantin dengan motif tradisional dan modern. Menggunakan henna berkualitas tinggi dan aman untuk kulit sensitif.</p><p><strong>Henna Styles:</strong></p><ul><li>Arabic traditional pattern</li><li>Indian bridal design</li><li>Modern minimalist</li><li>Custom request design</li><li>Bridal party service</li></ul>',
                'harga_publish' => 1500000,
                'harga_vendor' => 1200000,
                'bank_name' => 'CIMB Niaga',
                'bank_account' => '5678012345',
                'account_holder' => 'Fatimah Art Henna',
            ],
            [
                'name' => 'Security Wedding Service',
                'slug' => 'security-wedding-service',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Joko Security',
                'phone' => '8678012345',
                'address' => 'Jl. Pancoran No. 654, Jakarta Selatan',
                'description' => '<p>Layanan security profesional untuk wedding dengan personel terlatih dan berpengalaman. Menjamin keamanan acara dan tamu dengan protokol keamanan standar.</p><p><strong>Security Package:</strong></p><ul><li>Personal security</li><li>Crowd control</li><li>Parking management</li><li>Gift security</li><li>Emergency response</li></ul>',
                'harga_publish' => 2800000,
                'harga_vendor' => 2300000,
                'bank_name' => 'Danamon',
                'bank_account' => '6780123456',
                'account_holder' => 'Joko Security Service',
            ],
            [
                'name' => 'Outdoor Wedding Specialist',
                'slug' => 'outdoor-wedding-specialist',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Budi Outdoor',
                'phone' => '8780123456',
                'address' => 'Jl. Puncak No. 987, Bogor',
                'description' => '<p>Spesialis wedding outdoor dengan venue taman dan pemandangan alam. Melayani garden party wedding dengan konsep rustic dan natural setting.</p><p><strong>Outdoor Venues:</strong></p><ul><li>Garden ceremony</li><li>Beach wedding setup</li><li>Mountain view venue</li><li>Rustic decoration</li><li>Weather backup plan</li></ul>',
                'harga_publish' => 18000000,
                'harga_vendor' => 14500000,
                'bank_name' => 'Permata',
                'bank_account' => '7801234567',
                'account_holder' => 'Budi Outdoor Wedding',
            ],
            [
                'name' => 'Live Music Band Wedding',
                'slug' => 'live-music-band-wedding',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Ricky Band',
                'phone' => '8801234567',
                'address' => 'Jl. Blok M No. 246, Jakarta Selatan',
                'description' => '<p>Live band profesional untuk wedding dengan repertoire lagu Indonesia dan Internasional. Formasi lengkap dengan vocal, guitar, bass, drum, dan keyboard.</p><p><strong>Music Genres:</strong></p><ul><li>Pop Indonesia</li><li>Jazz standards</li><li>Love songs</li><li>Acoustic session</li><li>Dance music</li></ul>',
                'harga_publish' => 8500000,
                'harga_vendor' => 7000000,
                'bank_name' => 'BCA',
                'bank_account' => '8012345678',
                'account_holder' => 'Ricky Music Entertainment',
            ],
            [
                'name' => 'Bridal Shoe Boutique',
                'slug' => 'bridal-shoe-boutique',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Maya Shoes',
                'phone' => '8012345679',
                'address' => 'Jl. Grand Indonesia No. 135, Jakarta Pusat',
                'description' => '<p>Boutique sepatu pengantin dengan koleksi designer shoes untuk wedding. Melayani custom order dan rental sepatu mewah dengan berbagai ukuran.</p><p><strong>Collection:</strong></p><ul><li>Designer bridal shoes</li><li>Custom heel height</li><li>Comfortable padding</li><li>Various colors</li><li>Rental & purchase</li></ul>',
                'harga_publish' => 2200000,
                'harga_vendor' => 1800000,
                'bank_name' => 'Mandiri',
                'bank_account' => '0123456790',
                'account_holder' => 'Maya Bridal Boutique',
            ],
            [
                'name' => 'Wedding Ring Designer',
                'slug' => 'wedding-ring-designer',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Toni Jewelry',
                'phone' => '8123456790',
                'address' => 'Jl. Cikini No. 468, Jakarta Pusat',
                'description' => '<p>Designer cincin kawin custom dengan berbagai material precious metal dan diamond. Melayani engrave personal message dan custom design sesuai keinginan.</p><p><strong>Materials:</strong></p><ul><li>18K gold collection</li><li>Platinum rings</li><li>Diamond setting</li><li>Custom engraving</li><li>Lifetime warranty</li></ul>',
                'harga_publish' => 15000000,
                'harga_vendor' => 12500000,
                'bank_name' => 'BRI',
                'bank_account' => '1234567900',
                'account_holder' => 'Toni Jewelry Design',
            ],
            [
                'name' => 'Traditional Kebaya Designer',
                'slug' => 'traditional-kebaya-designer',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Ibu Kartika',
                'phone' => '8234567900',
                'address' => 'Jl. Malioboro No. 579, Yogyakarta',
                'description' => '<p>Designer kebaya tradisional untuk pengantin dengan berbagai model daerah Indonesia. Menggunakan kain batik authentic dan bordiran tangan berkualitas tinggi.</p><p><strong>Kebaya Styles:</strong></p><ul><li>Kebaya Jawa traditional</li><li>Kebaya Sunda modern</li><li>Kebaya Bali elegant</li><li>Custom fitting</li><li>Premium materials</li></ul>',
                'harga_publish' => 5500000,
                'harga_vendor' => 4400000,
                'bank_name' => 'BNI',
                'bank_account' => '2345679001',
                'account_holder' => 'Kartika Kebaya House',
            ],
            [
                'name' => 'Wedding Transportation',
                'slug' => 'wedding-transportation',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Hendra Transport',
                'phone' => '8345679001',
                'address' => 'Jl. Soekarno Hatta No. 802, Bandung',
                'description' => '<p>Layanan transportasi wedding untuk tamu dan keluarga dengan armada bus dan minibus ber-AC. Melayani antar jemput dari hotel ke venue acara.</p><p><strong>Fleet Available:</strong></p><ul><li>Luxury bus 45 seat</li><li>Minibus 25 seat</li><li>Hiace 15 seat</li><li>Professional driver</li><li>Route planning</li></ul>',
                'harga_publish' => 3800000,
                'harga_vendor' => 3100000,
                'bank_name' => 'CIMB Niaga',
                'bank_account' => '3456790012',
                'account_holder' => 'Hendra Transportation',
            ],
            [
                'name' => 'Photo Booth Rental',
                'slug' => 'photo-booth-rental',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Dika Photo Booth',
                'phone' => '8456790012',
                'address' => 'Jl. Tebet No. 135, Jakarta Selatan',
                'description' => '<p>Rental photo booth untuk wedding dengan berbagai props dan background menarik. Dilengkapi dengan instant print dan digital gallery untuk guests.</p><p><strong>Photo Booth Package:</strong></p><ul><li>Instant photo printing</li><li>Digital copy gallery</li><li>Fun props collection</li><li>Custom backdrop</li><li>Social media sharing</li></ul>',
                'harga_publish' => 2800000,
                'harga_vendor' => 2300000,
                'bank_name' => 'Danamon',
                'bank_account' => '4567900123',
                'account_holder' => 'Dika Creative Booth',
            ],
            [
                'name' => 'Drone Wedding Video',
                'slug' => 'drone-wedding-video',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Arif Drone Pilot',
                'phone' => '8567900123',
                'address' => 'Jl. Fatmawati No. 246, Jakarta Selatan',
                'description' => '<p>Jasa drone videography untuk wedding dengan aerial shot spectacular. Menggunakan drone professional grade dan pilot bersertifikat untuk hasil cinematik terbaik.</p><p><strong>Drone Services:</strong></p><ul><li>4K aerial videography</li><li>Cinematic drone shots</li><li>Licensed drone pilot</li><li>Weather backup plan</li><li>Edited final video</li></ul>',
                'harga_publish' => 4500000,
                'harga_vendor' => 3600000,
                'bank_name' => 'Permata',
                'bank_account' => '5679001234',
                'account_holder' => 'Arif Drone Services',
            ],
            [
                'name' => 'Wedding Favor Specialist',
                'slug' => 'wedding-favor-specialist',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Sari Souvenir',
                'phone' => '8679001234',
                'address' => 'Jl. Mangga Besar No. 357, Jakarta Barat',
                'description' => '<p>Spesialis souvenir wedding dan door gift dengan berbagai pilihan unique dan personalized items. Melayani custom packaging dan personal message.</p><p><strong>Favor Options:</strong></p><ul><li>Personalized souvenirs</li><li>Traditional gift items</li><li>Modern favor boxes</li><li>Custom packaging</li><li>Bulk order discount</li></ul>',
                'harga_publish' => 3200000,
                'harga_vendor' => 2600000,
                'bank_name' => 'BCA',
                'bank_account' => '6790012345',
                'account_holder' => 'Sari Wedding Favor',
            ],
            [
                'name' => 'Ice Sculpture Art',
                'slug' => 'ice-sculpture-art',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Benny Ice Art',
                'phone' => '8790012345',
                'address' => 'Jl. Pluit No. 468, Jakarta Utara',
                'description' => '<p>Seniman ice sculpture untuk wedding dengan berbagai design custom dan artistic. Menggunakan es berkualitas food grade dengan holding time optimal untuk acara.</p><p><strong>Ice Art Services:</strong></p><ul><li>Custom ice sculpture</li><li>Food grade quality ice</li><li>Artistic design</li><li>Professional installation</li><li>Temperature maintenance</li></ul>',
                'harga_publish' => 4800000,
                'harga_vendor' => 3900000,
                'bank_name' => 'Mandiri',
                'bank_account' => '7900123456',
                'account_holder' => 'Benny Ice Sculpture',
            ],
            [
                'name' => 'Wedding Stationery Design',
                'slug' => 'wedding-stationery-design',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Lisa Stationery',
                'phone' => '8900123456',
                'address' => 'Jl. Bintaro No. 579, Jakarta Selatan',
                'description' => '<p>Designer stationery wedding lengkap dari save the date hingga thank you card. Melayani custom design dengan berbagai teknik printing premium dan finishing mewah.</p><p><strong>Stationery Package:</strong></p><ul><li>Save the date cards</li><li>Wedding invitations</li><li>RSVP cards</li><li>Menu cards</li><li>Thank you notes</li></ul>',
                'harga_publish' => 3500000,
                'harga_vendor' => 2800000,
                'bank_name' => 'BRI',
                'bank_account' => '9001234567',
                'account_holder' => 'Lisa Creative Stationery',
            ],
            [
                'name' => 'Bridal Hair Accessories',
                'slug' => 'bridal-hair-accessories',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Citra Accessories',
                'phone' => '8001234567',
                'address' => 'Jl. Kelapa Gading No. 680, Jakarta Utara',
                'description' => '<p>Boutique aksesoris rambut pengantin dengan koleksi tiara, hairpiece, dan veil berkualitas premium. Melayani custom order sesuai tema wedding dan dress pengantin.</p><p><strong>Hair Accessories:</strong></p><ul><li>Crystal tiara collection</li><li>Pearl hairpiece</li><li>Designer wedding veil</li><li>Hair clips & combs</li><li>Custom accessories</li></ul>',
                'harga_publish' => 2800000,
                'harga_vendor' => 2300000,
                'bank_name' => 'BNI',
                'bank_account' => '0012345678',
                'account_holder' => 'Citra Bridal Accessories',
            ],
            [
                'name' => 'Wedding Venue Garden',
                'slug' => 'wedding-venue-garden',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Pak Bambang',
                'phone' => '8112345678',
                'address' => 'Jl. Puncak Pass No. 791, Bogor',
                'description' => '<p>Venue wedding garden dengan pemandangan pegunungan dan udara sejuk. Kapasitas 300-600 tamu dengan fasilitas lengkap untuk outdoor dan indoor reception.</p><p><strong>Garden Facilities:</strong></p><ul><li>Scenic mountain view</li><li>Indoor/outdoor options</li><li>Gazebo ceremony area</li><li>Garden photo spots</li><li>Catering kitchen facility</li></ul>',
                'harga_publish' => 20000000,
                'harga_vendor' => 16000000,
                'bank_name' => 'CIMB Niaga',
                'bank_account' => '1123456789',
                'account_holder' => 'Bambang Garden Venue',
            ],
            [
                'name' => 'Professional Wedding MC',
                'slug' => 'professional-wedding-mc',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Andre MC',
                'phone' => '8223456789',
                'address' => 'Jl. Radio Dalam No. 892, Jakarta Selatan',
                'description' => '<p>MC profesional untuk wedding dengan pengalaman 10+ tahun dan gaya komunikasi yang engaging. Bilingual (Indonesia-English) dengan personality yang warm dan professional.</p><p><strong>MC Services:</strong></p><ul><li>Bilingual hosting</li><li>Program coordination</li><li>Guest interaction</li><li>Traditional ceremony</li><li>Modern reception style</li></ul>',
                'harga_publish' => 3800000,
                'harga_vendor' => 3100000,
                'bank_name' => 'Danamon',
                'bank_account' => '2234567890',
                'account_holder' => 'Andre Professional MC',
            ],
            [
                'name' => 'Wedding Balloon Decorator',
                'slug' => 'wedding-balloon-decorator',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Winda Balloon',
                'phone' => '8334567890',
                'address' => 'Jl. Sunter No. 993, Jakarta Utara',
                'description' => '<p>Dekorator balon wedding dengan berbagai konsep dan design modern. Menggunakan balon berkualitas tinggi dengan warna custom sesuai tema wedding couple.</p><p><strong>Balloon Decoration:</strong></p><ul><li>Balloon arch entrance</li><li>Centerpiece balloons</li><li>Photo backdrop</li><li>Ceiling installation</li><li>Custom color themes</li></ul>',
                'harga_publish' => 2500000,
                'harga_vendor' => 2000000,
                'bank_name' => 'Permata',
                'bank_account' => '3345678901',
                'account_holder' => 'Winda Balloon Art',
            ],
            [
                'name' => 'Wedding Perfume Signature',
                'slug' => 'wedding-perfume-signature',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Nadia Perfume',
                'phone' => '8445678901',
                'address' => 'Jl. PIK No. 104, Jakarta Utara',
                'description' => '<p>Creator signature perfume untuk wedding couple dengan custom scent yang personal dan memorable. Menggunakan essential oil premium dengan packaging elegant.</p><p><strong>Perfume Services:</strong></p><ul><li>Custom scent creation</li><li>Premium essential oils</li><li>Elegant packaging</li><li>Personal consultation</li><li>Wedding day supply</li></ul>',
                'harga_publish' => 1800000,
                'harga_vendor' => 1500000,
                'bank_name' => 'BCA',
                'bank_account' => '4456789012',
                'account_holder' => 'Nadia Signature Scent',
            ],
            [
                'name' => 'Honeymoon Travel Agent',
                'slug' => 'honeymoon-travel-agent',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Ryan Travel',
                'phone' => '8556789012',
                'address' => 'Jl. Menteng No. 215, Jakarta Pusat',
                'description' => '<p>Travel agent spesialis honeymoon package dengan destinasi romantis domestic dan international. Melayani custom itinerary sesuai budget dan preferensi couple.</p><p><strong>Honeymoon Packages:</strong></p><ul><li>Domestic romantic destinations</li><li>International honeymoon</li><li>Custom itinerary</li><li>Hotel & flight booking</li><li>Romantic activities</li></ul>',
                'harga_publish' => 25000000,
                'harga_vendor' => 20000000,
                'bank_name' => 'Mandiri',
                'bank_account' => '5567890123',
                'account_holder' => 'Ryan Honeymoon Travel',
            ],
            [
                'name' => 'Wedding Magician Entertainment',
                'slug' => 'wedding-magician-entertainment',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'David Magic',
                'phone' => '8667890123',
                'address' => 'Jl. Kemang No. 326, Jakarta Selatan',
                'description' => '<p>Magician profesional untuk entertainment wedding dengan pertunjukan close-up magic dan stage illusion. Menghadirkan surprise entertainment yang memorable untuk guests.</p><p><strong>Magic Shows:</strong></p><ul><li>Close-up magic performance</li><li>Stage illusion show</li><li>Interactive guest entertainment</li><li>Surprise elements</li><li>Professional showmanship</li></ul>',
                'harga_publish' => 4200000,
                'harga_vendor' => 3400000,
                'bank_name' => 'BRI',
                'bank_account' => '6678901234',
                'account_holder' => 'David Magic Entertainment',
            ],
            [
                'name' => 'Wedding Tent Rental',
                'slug' => 'wedding-tent-rental',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Jaya Tenda',
                'phone' => '8778901234',
                'address' => 'Jl. Cakung No. 437, Jakarta Timur',
                'description' => '<p>Rental tenda wedding untuk outdoor event dengan berbagai ukuran dan design elegant. Melayani full setup dengan flooring, lighting, dan dekorasi tenda professional.</p><p><strong>Tent Options:</strong></p><ul><li>Various tent sizes</li><li>Elegant tent design</li><li>Professional flooring</li><li>Lighting installation</li><li>Weather protection</li></ul>',
                'harga_publish' => 8500000,
                'harga_vendor' => 7000000,
                'bank_name' => 'BNI',
                'bank_account' => '7789012345',
                'account_holder' => 'Jaya Tent Rental',
            ],
            [
                'name' => 'Bridal Spa Treatment',
                'slug' => 'bridal-spa-treatment',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Lina Spa',
                'phone' => '8889012345',
                'address' => 'Jl. Senayan No. 548, Jakarta Selatan',
                'description' => '<p>Spa treatment khusus pengantin dengan paket lengkap pre-wedding beauty preparation. Menggunakan produk premium dan therapist bersertifikat international.</p><p><strong>Bridal Spa Package:</strong></p><ul><li>Pre-wedding facial treatment</li><li>Body whitening therapy</li><li>Relaxation massage</li><li>Mani-pedi premium</li><li>Hair treatment spa</li></ul>',
                'harga_publish' => 3500000,
                'harga_vendor' => 2800000,
                'bank_name' => 'CIMB Niaga',
                'bank_account' => '8890123456',
                'account_holder' => 'Lina Bridal Spa',
            ],
            [
                'name' => 'Wedding Furniture Rental',
                'slug' => 'wedding-furniture-rental',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Adi Furniture',
                'phone' => '8990123456',
                'address' => 'Jl. Ragunan No. 659, Jakarta Selatan',
                'description' => '<p>Rental furniture wedding dengan koleksi meja, kursi, dan dekorasi furniture elegant. Melayani setup complete dengan design konsep sesuai tema wedding.</p><p><strong>Furniture Collection:</strong></p><ul><li>Elegant table & chairs</li><li>Lounge furniture sets</li><li>Decorative furniture</li><li>Setup & breakdown</li><li>Various style themes</li></ul>',
                'harga_publish' => 6500000,
                'harga_vendor' => 5200000,
                'bank_name' => 'Danamon',
                'bank_account' => '9901234567',
                'account_holder' => 'Adi Wedding Furniture',
            ],
            [
                'name' => 'Wedding Videographer Cinematic',
                'slug' => 'wedding-videographer-cinematic',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Reza Video',
                'phone' => '8091234567',
                'address' => 'Jl. Serpong No. 760, Tangerang',
                'description' => '<p>Videographer wedding dengan specialty cinematic storytelling dan emotional moments capture. Menggunakan equipment professional dan post-production editing advanced.</p><p><strong>Video Services:</strong></p><ul><li>Cinematic wedding film</li><li>Same day edit</li><li>Highlight reel</li><li>Full ceremony coverage</li><li>Professional color grading</li></ul>',
                'harga_publish' => 9500000,
                'harga_vendor' => 7600000,
                'bank_name' => 'Permata',
                'bank_account' => '0912345678',
                'account_holder' => 'Reza Cinematic Video',
            ],
            [
                'name' => 'Wedding Gown Designer Couture',
                'slug' => 'wedding-gown-designer-couture',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Ibu Siska',
                'phone' => '8192345678',
                'address' => 'Jl. Pondok Indah No. 871, Jakarta Selatan',
                'description' => '<p>Designer wedding gown couture dengan custom fitting dan design eksklusif. Menggunakan fabric premium imported dan handmade details dengan craftsmanship tinggi.</p><p><strong>Couture Services:</strong></p><ul><li>Custom wedding gown design</li><li>Premium fabric selection</li><li>Perfect fitting sessions</li><li>Handmade details</li><li>Exclusive design guarantee</li></ul>',
                'harga_publish' => 18000000,
                'harga_vendor' => 14500000,
                'bank_name' => 'BCA',
                'bank_account' => '1923456789',
                'account_holder' => 'Siska Couture Bridal',
            ],
            [
                'name' => 'Wedding Reception Coordinator',
                'slug' => 'wedding-reception-coordinator',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Tia Coordinator',
                'phone' => '8293456789',
                'address' => 'Jl. Gatot Subroto No. 982, Jakarta Selatan',
                'description' => '<p>Reception coordinator profesional untuk wedding day execution dengan detail management dan timeline coordination. Memastikan smooth running acara dari preparation hingga closing.</p><p><strong>Coordination Services:</strong></p><ul><li>Day-of coordination</li><li>Vendor management</li><li>Timeline execution</li><li>Guest assistance</li><li>Emergency handling</li></ul>',
                'harga_publish' => 4500000,
                'harga_vendor' => 3600000,
                'bank_name' => 'Mandiri',
                'bank_account' => '2934567890',
                'account_holder' => 'Tia Wedding Coordinator',
            ],
            [
                'name' => 'Traditional Dance Performance',
                'slug' => 'traditional-dance-performance',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Sari Tari',
                'phone' => '8394567890',
                'address' => 'Jl. Taman Mini No. 093, Jakarta Timur',
                'description' => '<p>Grup tari tradisional Indonesia untuk wedding ceremony dengan berbagai tarian daerah. Menghadirkan cultural performance yang elegant dan meaningful untuk acara pernikahan.</p><p><strong>Dance Performances:</strong></p><ul><li>Javanese traditional dance</li><li>Balinese welcome dance</li><li>Minang ceremonial dance</li><li>Betawi cultural performance</li><li>Custom regional dance</li></ul>',
                'harga_publish' => 3800000,
                'harga_vendor' => 3100000,
                'bank_name' => 'BRI',
                'bank_account' => '3945678901',
                'account_holder' => 'Sari Traditional Dance',
            ],
            [
                'name' => 'Wedding Dessert Table',
                'slug' => 'wedding-dessert-table',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Chef Dinda',
                'phone' => '8495678901',
                'address' => 'Jl. Ampera No. 194, Jakarta Selatan',
                'description' => '<p>Spesialis dessert table wedding dengan berbagai macam dessert premium dan presentation yang elegant. Menggunakan ingredients berkualitas tinggi dan design yang Instagram-worthy.</p><p><strong>Dessert Collection:</strong></p><ul><li>Premium macarons</li><li>Mini cheesecakes</li><li>Chocolate fountain</li><li>Custom dessert design</li><li>Beautiful table setup</li></ul>',
                'harga_publish' => 4800000,
                'harga_vendor' => 3900000,
                'bank_name' => 'BNI',
                'bank_account' => '4956789012',
                'account_holder' => 'Dinda Dessert Table',
            ],
            [
                'name' => 'Wedding Fireworks Display',
                'slug' => 'wedding-fireworks-display',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Eko Fireworks',
                'phone' => '8596789012',
                'address' => 'Jl. Karawaci No. 295, Tangerang',
                'description' => '<p>Penyedia fireworks display untuk wedding dengan berbagai jenis kembang api dan safety protocol yang ketat. Menghadirkan spectacular closing ceremony yang memorable.</p><p><strong>Fireworks Package:</strong></p><ul><li>Professional fireworks display</li><li>Safety protocol compliance</li><li>Timed choreography</li><li>Various firework types</li><li>Grand finale effects</li></ul>',
                'harga_publish' => 12000000,
                'harga_vendor' => 9600000,
                'bank_name' => 'CIMB Niaga',
                'bank_account' => '5967890123',
                'account_holder' => 'Eko Fireworks Display',
            ],
            [
                'name' => 'Wedding Calligraphy Service',
                'slug' => 'wedding-calligraphy-service',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Maya Calligraphy',
                'phone' => '8697890123',
                'address' => 'Jl. Benda No. 396, Jakarta Selatan',
                'description' => '<p>Jasa calligraphy untuk wedding invitation dan signage dengan berbagai style tulisan tangan yang elegant. Melayani custom lettering untuk personal touch pada stationery wedding.</p><p><strong>Calligraphy Services:</strong></p><ul><li>Hand lettered invitations</li><li>Wedding signage</li><li>Place cards</li><li>Custom quotes design</li><li>Various lettering styles</li></ul>',
                'harga_publish' => 2800000,
                'harga_vendor' => 2300000,
                'bank_name' => 'Danamon',
                'bank_account' => '6978901234',
                'account_holder' => 'Maya Calligraphy Art',
            ],
            [
                'name' => 'Wedding Live Streaming',
                'slug' => 'wedding-live-streaming',
                'category_id' => $categories->random()->id,
                'status' => 'vendor',
                'pic_name' => 'Digital Stream',
                'phone' => '8798901234',
                'address' => 'Jl. Cilandak No. 497, Jakarta Selatan',
                'description' => '<p>Layanan live streaming wedding untuk keluarga dan teman yang tidak bisa hadir secara physical. Menggunakan multi-camera setup dan professional broadcasting equipment.</p><p><strong>Streaming Package:</strong></p><ul><li>Multi-camera live stream</li><li>Professional broadcasting</li><li>Interactive chat feature</li><li>Recording backup</li><li>Social media integration</li></ul>',
                'harga_publish' => 3500000,
                'harga_vendor' => 2800000,
                'bank_name' => 'Permata',
                'bank_account' => '7989012345',
                'account_holder' => 'Digital Stream Service',
            ],
        ];

        foreach ($vendors as $vendorData) {
            Vendor::firstOrCreate(
                [
                    'name' => $vendorData['name'],
                    'slug' => $vendorData['slug'],
                ],
                $vendorData
            );
        }

        $this->command->info('50 vendors created successfully!');
    }
}
