/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    safelist: [
        // Status badge colors
        "bg-green-100",
        "bg-yellow-100",
        "bg-red-100",
        "bg-gray-100",
        "text-green-800",
        "text-yellow-800",
        "text-red-800",
        "text-gray-800",
        "border-green-200",
        "border-yellow-200",
        "border-red-200",
        "border-gray-200",
        // Button colors for invoice page
        "bg-green-600",
        "bg-green-500",
        "hover:bg-green-500",
        "focus:ring-green-500",
        "ring-green-500",
        "bg-emerald-600",
        "bg-emerald-500",
        "hover:bg-emerald-500",
        "focus:ring-emerald-500",
        "ring-emerald-500",
        // Progress bar colors - high contrast
        "bg-emerald-500",
        "bg-amber-500",
        "bg-red-500",
        "bg-gray-200",
        "bg-gray-300",
        "bg-gray-400",
        "shadow-emerald-300",
        "shadow-amber-300",
        "shadow-red-300",
        "text-emerald-600",
        "bg-red-50",
        // Button gradient classes
        "bg-gradient-to-r",
        "from-purple-600",
        "to-purple-700",
        "hover:from-purple-700",
        "hover:to-purple-800",
        "from-blue-50",
        "to-blue-100",
        "hover:from-blue-100",
        "hover:to-blue-200",
        "from-yellow-50",
        "to-yellow-100",
        "hover:from-yellow-100",
        "hover:to-yellow-200",
        "from-gray-50",
        "to-gray-100",
        // City Cards Gradients
        "from-blue-600",
        "to-blue-800",
        "from-orange-600",
        "to-orange-800",
        "from-green-600",
        "to-green-800",
        // Text colors
        "text-white",
        "text-blue-700",
        "text-yellow-700",
        "text-gray-600",
        // Border colors
        "border-blue-200",
        "border-yellow-200",
        "border-gray-200",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Poppins", "ui-sans-serif", "system-ui", "sans-serif"],
                poppins: ["Poppins", "sans-serif"],
            },
            colors: {
                "primary-black": "#1a1a1a",
                "primary-blue": "#1e40af",
                "primary-yellow": "#fbbf24",
                "accent-blue": "#3b82f6",
                "accent-yellow": "#f59e0b",
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
    ],
};
