<?php

return [
    'proyek-wedding' => [
        'slug' => 'proyek-wedding',
        'icon' => 'fa-ring',
        'color' => 'bg-sky-50 text-sky-700',
        'accent' => 'rgba(14, 165, 233, 0.18)',
        'title' => 'Proyek Wedding',
        'label' => 'Modul Proyek',
        'desc' => 'Kelola seluruh siklus proyek wedding dari prospek hingga acara selesai.',
        'hero' => 'Dari prospek pertama sampai hari H — semua tahapan proyek wedding terpantau rapi dalam satu alur.',
        'items' => [
            'Prospecting & quotation',
            'Order & kontrak',
            'Produk & paket',
            'Vendor',
            'Timeline & checklist',
            'Monitoring progress',
        ],
        'highlights' => [
            ['fa-comments', 'Kelola prospek', 'Catat follow-up, status, dan peluang closing dari satu tempat.'],
            ['fa-file-contract', 'Order & kontrak', 'Ubah deal menjadi order dengan dokumen dan status yang jelas.'],
            ['fa-box-open', 'Paket & vendor', 'Susun paket produk dan koordinasikan vendor per proyek.'],
            ['fa-list-check', 'Timeline operasional', 'Checklist dan progress proyek terlihat real-time oleh tim.'],
        ],
        'audience' => ['Owner', 'Account Manager', 'Event Manager'],
    ],

    'keuangan' => [
        'slug' => 'keuangan',
        'icon' => 'fa-chart-line',
        'color' => 'bg-emerald-50 text-emerald-700',
        'accent' => 'rgba(16, 185, 129, 0.18)',
        'title' => 'Keuangan',
        'label' => 'Modul Keuangan',
        'desc' => 'Pantau arus kas, pendapatan, pengeluaran, dan laporan laba rugi secara real-time.',
        'hero' => 'Keuangan wedding organizer jadi lebih transparan — dari pembayaran klien hingga laporan laba rugi.',
        'items' => [
            'Pencatatan klien',
            'Pengeluaran proyek',
            'Piutang & hutang',
            'Laporan laba rugi',
            'Cash flow',
            'Budgeting',
        ],
        'highlights' => [
            ['fa-money-bill-wave', 'Pendapatan klien', 'Catat pembayaran, termin, dan sisa tagihan per proyek.'],
            ['fa-receipt', 'Pengeluaran proyek', 'Pantau biaya vendor dan operasional per event.'],
            ['fa-scale-balanced', 'Laba rugi', 'Lihat performa keuangan tanpa spreadsheet terpisah.'],
            ['fa-wallet', 'Arus kas', 'Pantau cash flow perusahaan secara real-time.'],
        ],
        'audience' => ['Owner', 'Finance', 'Account Manager'],
    ],

    'rekonsiliasi' => [
        'slug' => 'rekonsiliasi',
        'icon' => 'fa-building-columns',
        'color' => 'bg-teal-50 text-teal-700',
        'accent' => 'rgba(20, 184, 166, 0.18)',
        'title' => 'Rekonsiliasi Rekening Koran',
        'label' => 'Modul Rekonsiliasi',
        'desc' => 'Cocokkan transaksi bank dengan sistem lebih cepat dan akurat.',
        'hero' => 'Rekonsiliasi rekening koran lebih cepat dengan pencocokan otomatis dan laporan selisih yang jelas.',
        'items' => [
            'Import rekening koran',
            'Auto-matching',
            'Identifikasi selisih',
            'Multi-rekening',
            'Laporan rekonsiliasi',
        ],
        'highlights' => [
            ['fa-file-import', 'Import mutasi', 'Tarik atau unggah rekening koran multi-bank.'],
            ['fa-link', 'Auto-matching', 'Cocokkan transaksi bank dengan catatan sistem secara otomatis.'],
            ['fa-triangle-exclamation', 'Deteksi selisih', 'Temukan transaksi belum cocok lebih cepat.'],
            ['fa-chart-column', 'Laporan bersih', 'Hasil rekonsiliasi siap diaudit kapan saja.'],
        ],
        'audience' => ['Finance', 'Owner'],
    ],

    'nota-dinas' => [
        'slug' => 'nota-dinas',
        'icon' => 'fa-file-lines',
        'color' => 'bg-orange-50 text-orange-700',
        'accent' => 'rgba(249, 115, 22, 0.16)',
        'title' => 'Nota Dinas Digital',
        'label' => 'Modul Nota Dinas',
        'desc' => 'Ajukan, setujui, dan arsipkan nota dinas beserta lampiran dokumen.',
        'hero' => 'Pengajuan dan approval nota dinas berjalan digital — transparan, terarsip, dan mudah dilacak.',
        'items' => [
            'Pengajuan nota dinas',
            'Approval bertingkat',
            'Tracking status',
            'Riwayat pengajuan',
            'Lampiran dokumen',
        ],
        'highlights' => [
            ['fa-paper-plane', 'Pengajuan digital', 'Buat nota dinas lengkap dengan lampiran dari mana saja.'],
            ['fa-sitemap', 'Approval bertingkat', 'Alur persetujuan mengikuti hierarki jabatan.'],
            ['fa-route', 'Tracking status', 'Pantau posisi dokumen hingga selesai.'],
            ['fa-box-archive', 'Arsip rapi', 'Semua riwayat tersimpan dan mudah dicari kembali.'],
        ],
        'audience' => ['Staff', 'Finance', 'Owner'],
    ],

    'absensi' => [
        'slug' => 'absensi',
        'icon' => 'fa-location-dot',
        'color' => 'bg-blue-50 text-blue-700',
        'accent' => 'rgba(37, 99, 235, 0.16)',
        'title' => 'Absensi Kantor',
        'label' => 'Modul Absensi',
        'desc' => 'Absensi berbasis GPS dengan kontrol lokasi dan rekap real-time.',
        'hero' => 'Absensi kantor lebih terkontrol dengan GPS geofence, selfie, dan rekap kehadiran real-time.',
        'items' => [
            'GPS geofence',
            'Selfie anti-fraud',
            'Jadwal shift',
            'Koreksi absensi',
            'Lembur',
            'Rekap real-time',
        ],
        'highlights' => [
            ['fa-map-location-dot', 'GPS geofence', 'Absensi hanya valid di lokasi yang ditentukan.'],
            ['fa-camera', 'Selfie anti-fraud', 'Kurangi manipulasi kehadiran dengan verifikasi foto.'],
            ['fa-calendar-days', 'Jadwal & shift', 'Atur jadwal kerja dan penugasan tim dengan jelas.'],
            ['fa-clipboard-list', 'Rekap otomatis', 'Data absensi langsung siap untuk payroll dan laporan.'],
        ],
        'audience' => ['HRD', 'Staff', 'Owner'],
    ],

    'cuti-payroll' => [
        'slug' => 'cuti-payroll',
        'icon' => 'fa-wallet',
        'color' => 'bg-violet-50 text-violet-700',
        'accent' => 'rgba(139, 92, 246, 0.16)',
        'title' => 'Cuti & Payroll',
        'label' => 'Modul HR Finance',
        'desc' => 'Kelola cuti karyawan dan proses payroll hingga slip gaji digital.',
        'hero' => 'Dari pengajuan cuti sampai slip gaji — proses HR dan payroll jadi lebih cepat dan akurat.',
        'items' => [
            'Pengajuan & approval cuti',
            'Perhitungan payroll',
            'Slip gaji digital',
            'PPh 21',
            'Laporan payroll',
        ],
        'highlights' => [
            ['fa-plane-departure', 'Cuti digital', 'Ajuan, sisa kuota, dan approval cuti dalam satu alur.'],
            ['fa-calculator', 'Payroll akurat', 'Hitung gaji dengan komponen yang terstruktur.'],
            ['fa-file-invoice-dollar', 'Slip gaji', 'Karyawan menerima slip digital dengan mudah.'],
            ['fa-percent', 'PPh 21', 'Perhitungan pajak karyawan lebih tertib dan terdokumentasi.'],
        ],
        'audience' => ['HRD', 'Finance', 'Owner'],
    ],

    'portal-karyawan' => [
        'slug' => 'portal-karyawan',
        'icon' => 'fa-user-group',
        'color' => 'bg-green-50 text-green-700',
        'accent' => 'rgba(34, 197, 94, 0.16)',
        'title' => 'Portal Karyawan',
        'label' => 'Modul Self-Service',
        'desc' => 'Self-service untuk profil, absensi, cuti, dan slip gaji karyawan.',
        'hero' => 'Karyawan mengakses data pribadi, ajuan, dan slip gaji secara mandiri tanpa antre ke HRD.',
        'items' => [
            'Profil karyawan',
            'Riwayat absensi',
            'Ajuan cuti & lembur',
            'Slip gaji',
            'Pengumuman perusahaan',
        ],
        'highlights' => [
            ['fa-id-badge', 'Profil mandiri', 'Karyawan melihat dan memperbarui data yang diizinkan.'],
            ['fa-clock-rotate-left', 'Riwayat absensi', 'Cek kehadiran, keterlambatan, dan rekap pribadi.'],
            ['fa-inbox', 'Ajuan cepat', 'Cuti dan lembur diajukan langsung dari portal.'],
            ['fa-bullhorn', 'Pengumuman', 'Informasi perusahaan tersampaikan lebih merata.'],
        ],
        'audience' => ['Seluruh Karyawan', 'HRD'],
    ],

    'dokumen-sop' => [
        'slug' => 'dokumen-sop',
        'icon' => 'fa-folder-open',
        'color' => 'bg-rose-50 text-rose-700',
        'accent' => 'rgba(244, 63, 94, 0.14)',
        'title' => 'Dokumen & SOP',
        'label' => 'Modul Dokumen',
        'desc' => 'Simpan SOP, template, dan panduan kerja dalam satu knowledge base.',
        'hero' => 'SOP, template, dan panduan kerja tersusun rapi — mudah diakses sesuai hak masing-masing tim.',
        'items' => [
            'SOP & kebijakan',
            'Template dokumen',
            'Panduan kerja',
            'Knowledge base',
            'Akses terstruktur',
        ],
        'highlights' => [
            ['fa-book', 'SOP terpusat', 'Standar kerja tersedia dan selalu versi terbaru.'],
            ['fa-copy', 'Template siap pakai', 'Kurangi waktu membuat dokumen berulang.'],
            ['fa-graduation-cap', 'Knowledge base', 'Onboarding dan panduan kerja lebih konsisten.'],
            ['fa-user-lock', 'Akses terkontrol', 'Dokumen hanya terbuka untuk peran yang berwenang.'],
        ],
        'audience' => ['Owner', 'HRD', 'Event Manager'],
    ],

    'hak-akses' => [
        'slug' => 'hak-akses',
        'icon' => 'fa-shield-halved',
        'color' => 'bg-amber-50 text-amber-700',
        'accent' => 'rgba(201, 162, 39, 0.22)',
        'title' => 'Hak Akses Berdasarkan Peran',
        'label' => 'Modul Keamanan',
        'desc' => 'Kontrol akses fleksibel sesuai jabatan dengan jejak audit lengkap.',
        'hero' => 'Setiap peran melihat dan mengerjakan hanya apa yang menjadi tanggung jawabnya — aman dan tertelusur.',
        'items' => [
            'Role & permission',
            'Level akses fleksibel',
            'Approval hierarkis',
            'Keamanan data',
            'Audit trail',
        ],
        'highlights' => [
            ['fa-user-shield', 'Role & permission', 'Atur hak akses per jabatan dengan granular.'],
            ['fa-layer-group', 'Level fleksibel', 'Sesuaikan akses saat struktur organisasi berubah.'],
            ['fa-code-branch', 'Approval hierarkis', 'Alur persetujuan mengikuti struktur jabatan.'],
            ['fa-clock-rotate-left', 'Audit trail', 'Setiap aktivitas penting tercatat untuk audit.'],
        ],
        'audience' => ['Owner', 'HRD', 'IT / Admin'],
    ],
];
